<?php

/*
 * Demo içerik — iki dergi, dörder makaleli iki sayı (Kıyı: edebiyat ve kültür; Düşünce Atlası:
 * felsefe ve bilim). LibraryDemoSeeder okur. Yazar anahtarları LibraryDemoSeeder::AUTHORS'taki
 * e-posta adlarıdır. Blok sözdizimi kitaplardaki gibi.
 */

return [
    [
        'name' => 'Kıyı',
        'description' => 'Edebiyat, kültür ve gündelik hayat üzerine iki ayda bir yayımlanan bir dergi. Her sayı bir kelimenin etrafında toplanır: deniz, yol, ev, ses…',
        'issues' => [
            [
                'number' => 1,
                'title' => 'Kıyı - Sayı 1: Deniz',
                'days_ago' => 62,
                'editor_note' => 'İlk sayımızı denize ayırdık. Çünkü bu topraklarda yaşayan hemen herkesin bir deniz hikâyesi vardır: bir çocukluk yazı, bir vapur yolculuğu, bir limanda beklenen biri. Bu sayıdaki yazılar denizi şiirde, bir liman kentinin hafızasında ve denizcilerin dilinde arıyor. İyi okumalar.',
                'articles' => [
                    [
                        'title' => 'Denizle Yazılan Şiir',
                        'author' => 'elif.nazli',
                        'category' => 'Şiir',
                        'blocks' => [
                            'Türkçe şiirde denizin yeri, bir manzaradan çok bir ruh halidir. Şairler denizi anlatırken çoğu zaman suyu, dalgayı, martıyı değil; özlemi, uzaklığı, bir türlü varılamayan bir yeri anlatır. Deniz, şiirde hem bir kapı hem bir duvardır: bir yandan sonsuz bir açılma, öte yandan aşılamayan bir sınır.',
                            '## Açık Deniz',
                            'Yahya Kemal\'in "Açık Deniz" şiiri, bu ikiliği belki en iyi yakalayan şiirlerden biridir. Şair, dar bir hayattan, kapalı bir mekândan kurtulma arzusunu açık denize bağlar. Deniz burada bir kaçış yolu değil, ruhun asıl ait olduğu yerdir. Yahya Kemal\'in şiirlerinde İstanbul\'un suları, Boğaz\'ın akıntıları, Marmara\'nın ışığı sürekli geri döner; ama bu sular hep bir geçmişin, kaybolmuş bir zamanın da sularıdır.',
                            'Yahya Kemal\'de deniz aynı zamanda bir ses ve ritimdir. Aruz veznini Türkçenin doğal söyleyişiyle buluşturmaya çalışan şair için dalgaların düzenli gidiş gelişi, dizenin ölçüsüyle akraba gibidir. Onun şiirlerini sesli okuduğunuzda, kelimelerin bir dalga gibi yükselip çekildiğini hissedersiniz.',
                            '## Gidilmemiş Deniz',
                            'Nazım Hikmet\'in çok bilinen dizelerinde en güzel deniz, henüz gidilmemiş olanıdır. Bu dizeler, denizi bir umut imgesine dönüştürür. Gidilmemiş deniz, yaşanmamış günler, henüz yazılmamış sözlerle aynı sıraya girer. Hapiste yazılmış olması, dizelere ayrı bir ağırlık katar: dört duvar arasında denizi düşünmek, özgürlüğü düşünmektir.',
                            'Nazım\'ın şiirinde deniz çoğu zaman bir mektup gibidir: uzaktaki sevgiliye, uzaktaki şehre, uzaktaki geleceğe gönderilen bir haber. Bu yüzden onun denizleri hiçbir zaman durgun değildir; hep bir yolculuğun, bir kavuşmanın ya da bir ayrılığın içindedir.',
                            '> Şiirde deniz hiçbir zaman yalnızca sudur. Ya bir uzaklıktır, ya bir bekleyiş, ya da bir kurtuluş.',
                            '## Ada ve Öykü',
                            'Şiirin yanında, öykünün de bir denizi vardır. Sait Faik Abasıyanık\'ın Burgazada\'sı, Türk edebiyatının en sevilen kıyılarından biridir. Sait Faik\'in balıkçıları, kahvecileri, kimsesiz çocukları, hepsi denize bakan insanlardır. Onun öykülerinde deniz, bir süs değil, hayatın kendisidir; geçimin, sevginin, yalnızlığın kaynağı.',
                            'Sait Faik\'i okurken fark ettiğim bir şey, onun denizi hiçbir zaman büyük harflerle yazmamasıdır. Onun denizi küçük bir koyun durgun suyu, bir sandalın kenarına çarpan hafif dalga, sabahın erken saatinde ağ toplayan bir balıkçının elleridir. Belki de bu yüzden bu kadar yakın ve bu kadar gerçektir.',
                            '## Bugünün Denizi',
                            'Bugün yazılan şiirde deniz nasıl bir yer tutuyor? Şehirlerin büyüdüğü, kıyıların betonla kaplandığı, denizin çoğu zaman bir tatil broşürüne indirgendiği bir çağda, şairlerin denize bakışı da değişiyor. Kimi şairler denizin kirlenmesini, kıyıların kaybolmasını yazıyor; kimi ise denizi bir hatıra, bir çocukluk mekânı olarak koruyor.',
                            'Belki de şiirin denize karşı borcu şudur: Onu hatırlamak. Beton kıyıların, kalabalık plajların, turistik limanların ötesinde, bir zamanlar şairlere ilham veren o sonsuz, derin, gizemli suyu hatırlamak ve hatırlatmak.',
                            'Bu yazıyı bir öneriyle bitirmek istiyorum: Bir akşamüstü, bir kıyıda, sevdiğiniz bir deniz şiirini sesli okuyun. Dalgaların sesi ile dizelerin sesi birbirine karıştığında, şiirin neden hep denize döndüğünü anlayacaksınız.',
                        ],
                    ],
                    [
                        'title' => 'Bir Liman Kentinin Hafızası',
                        'author' => 'orhan.demir',
                        'category' => 'Tarih',
                        'blocks' => [
                            'Liman kentleri, kara şehirlerinden farklı hatırlar. Onların hafızasında gemi düdükleri, farklı dillerde yapılan pazarlıklar, uzak limanlardan gelen yükler ve bir daha dönmeyen yolcular vardır. Bir liman kenti, dünyaya açık bir kapıdır ve bu kapıdan yalnızca mallar değil, insanlar, fikirler ve hikâyeler de geçer.',
                            'Bu yazıda, Ege\'nin en büyük liman kentlerinden biri olan İzmir\'in hafızasına, bir yürüyüşçünün gözüyle bakmak istiyorum.',
                            '## Kordon',
                            'İzmir\'in denizle ilişkisini anlamak için Kordon\'dan başlamak gerekir. Bugün kentin en sevilen yürüyüş yeri olan bu kıyı şeridi, on dokuzuncu yüzyılın son çeyreğinde denizin doldurulmasıyla oluşturuldu.[[dn:Kordon\'un yapımı, liman ve rıhtım inşaatı için imtiyaz alan bir Fransız şirketi tarafından yürütüldü. Rıhtım, gemilerin doğrudan kıyıya yanaşabilmesini sağlayarak kentin ticaretini büyük ölçüde hızlandırdı.]] Rıhtımın yapılmasıyla gemiler doğrudan kıyıya yanaşabildi, kentin ticareti hızla büyüdü.',
                            'Kordon boyunca sıralanan binalar, o dönemin zenginliğini ve çok kültürlü yapısını yansıtıyordu: konsolosluklar, ticaret evleri, kulüpler, oteller. Bu binaların önünde farklı dillerde konuşan tüccarlar, denizciler, hamallar ve gezginler dolaşırdı.',
                            '## Kaybolan Kent',
                            'İzmir\'in hafızasının en acı sayfalarından biri, 1922 yangınıdır. Eylül ayında başlayan yangın, günlerce sürdü ve kentin büyük bir bölümünü yok etti. Kordon\'daki pek çok bina, çarşının bir kısmı ve bazı mahalleler tamamen yandı.',
                            'Yangından sonra kent yeniden inşa edildi. Yanan alanların bir kısmına bugünkü Kültürpark yapıldı. Yeni caddeler açıldı, yeni binalar dikildi. Ama yangından önceki İzmir, yalnızca fotoğraflarda, kartpostallarda ve anılarda kaldı.',
                            '> Bir liman kenti, kaybettiği binaları hatırlamaz belki, ama kaybettiği sesleri hatırlar: bir dilin, bir şarkının, bir satıcının seslenişinin artık duyulmadığı sokakları.',
                            '## Kemeraltı',
                            'Kordon\'dan kentin içine doğru yürüdüğünüzde, Kemeraltı Çarşısı\'na varırsınız. Dar sokakları, hanları, camileri, sinagogları ve kiliseleriyle Kemeraltı, İzmir\'in eski ticaret merkezinin bugüne kalan en canlı parçasıdır.',
                            'Kemeraltı\'nda yürürken, bir liman kentinin çok katmanlı hafızasını hissedebilirsiniz. Bir yanda Osmanlı döneminden kalma hanlar, bir yanda eski bir sinagog, bir yanda yeni açılmış bir kahveci. Esnaf, yüzyıllardır aynı sokaklarda aynı işi yapmaya devam ediyor: kumaş, baharat, altın, bakır.',
                            '## Hafızayı Korumak',
                            'Liman kentlerinin hafızası kırılgandır. Limanların modernleşmesi, konteyner terminallerinin kentten uzağa taşınması, eski rıhtımların dönüştürülmesi, bu hafızanın bir kısmını siliyor. Bugün pek çok liman kentinde eski liman bölgeleri alışveriş merkezlerine, lüks konutlara, turistik alanlara dönüşüyor.',
                            'Bu dönüşümlerin bir kısmı kaçınılmaz. Ama bir kentin denizle olan ilişkisini, limanıyla kurduğu bağı, o limandan geçen insanların hikâyelerini hatırlamak, bir kentin kimliğini korumanın yollarından biri.',
                            'Kordon\'da akşamüstü yürürken, güneşin körfezin üstüne battığı saatlerde, bu hafızayı hissetmek mümkün. Belki bir gemi düdüğünde, belki bir balıkçının ağ toplamasında, belki de yalnızca denizin kıyıya vuran sesinde.',
                        ],
                    ],
                    [
                        'title' => 'Tuzlu Kelimeler: Denizcilik Terimleri Üzerine',
                        'author' => 'murat.ekin',
                        'category' => 'Deneme',
                        'blocks' => [
                            'Balıkçı barınağında, yaşlı bir reisin teknesini onarmasını izlerken, kullandığı kelimelerin çoğunu anlamadığımı fark ettim. "Pruvayı biraz iskeleye al," dedi yamağına. "Pupadan halatı ver." "Fortuna geliyor, tente bağla." Türkçe konuşuyordu ama sanki başka bir dil de konuşuyordu. Denizin dili.',
                            'Bu dilin kelimelerinin önemli bir kısmının Türkçeye başka dillerden geldiğini sonradan öğrendim. Akdeniz yüzyıllar boyunca farklı halkların buluştuğu, ticaret yaptığı, savaştığı ve birlikte yaşadığı bir deniz oldu. Denizcilerin dili de bu buluşmadan doğdu.',
                            '## İtalyan Limanlarından',
                            'Türkçedeki denizcilik terimlerinin büyük bir bölümü İtalyancadan, özellikle de Venedik ve Ceneviz denizcilerinin konuştuğu lehçelerden gelir. Bu şaşırtıcı değil; Orta Çağ ve Rönesans döneminde bu iki denizci cumhuriyeti, Doğu Akdeniz ticaretinin en önemli oyuncularıydı.',
                            '"İskele" kelimesi, merdiven anlamına gelen İtalyanca "scala"dan gelir. Gemiden kıyıya inen tahta merdiven, zamanla gemilerin yanaştığı yerin kendisine ad olmuştur. Aynı kelime teknede sol yanı da anlatır; sağ yana ise "sancak" denir.[[dn:Teknede sol yana "iskele" denmesinin, eski gemilerin limana bu taraflarıyla yanaşmasından kaynaklandığı söylenir. Sağ taraftaki "sancak" ise Türkçe kökenlidir.]]',
                            '"Pruva" (teknenin baş tarafı) İtalyanca "prua"dan, "pupa" (kıç tarafı) ise "poppa"dan gelir. "Fortuna", fırtına anlamında, İtalyanca şans, talih anlamındaki "fortuna"dan türemiştir. Denizciler için talih ile fırtına arasındaki bu bağ, belki de hiç tesadüf değildir.',
                            '## Rum Kıyılarından',
                            'Denizcilik dilimizin bir başka önemli kaynağı Rumcadır. Bu da anlaşılır bir durum; Ege ve Karadeniz kıyılarında yüzyıllar boyunca Türk ve Rum denizciler, balıkçılar yan yana çalıştı.',
                            '"Liman" kelimesi Rumca "limani"den, "fener" ise "fanari"den gelir. Rüzgâr adlarının bir kısmı da eski Yunancaya kadar uzanır: kuzeyden esen soğuk "poyraz", eski Yunan mitolojisinde kuzey rüzgârının tanrısı Boreas\'ın adını taşır.',
                            'Balık adlarında da bu miras görülür. İstanbul ve Ege balıkçılarının kullandığı pek çok balık adı, Rumca kökenlidir. Bu adlar, yüzyıllar boyunca aynı sularda aynı balıkları avlayan toplulukların ortak bir dil geliştirdiğinin kanıtıdır.',
                            '> Denizcilerin dili, bir sözlükten çok bir haritaya benzer. Her kelime, geldiği limanı hatırlatır.',
                            '## Kaybolan Kelimeler',
                            'Ne yazık ki bu dilin bir kısmı kayboluyor. Ahşap tekne ustaları azaldıkça, geleneksel balıkçılık yerini endüstriyel avcılığa bıraktıkça, yelkenli teknelerin yerini motorlular aldıkça, bu kelimeleri kullanan insanlar da azalıyor.',
                            'Yaşlı reisin teknesini onarırken kullandığı kelimelerin bir kısmını gençler artık bilmiyor. Bir tekne parçasının adını, bir düğümün adını, bir rüzgârın adını. Bu kelimeler kaybolduğunda, onlarla birlikte bir bilgi, bir deneyim, bir dünya görüşü de kayboluyor.',
                            '## Tuzlu Bir Sözlük',
                            'O gün barınaktan ayrılırken, reisten öğrendiğim kelimeleri bir deftere yazdım. Sonraki haftalarda başka balıkçılarla, tekne ustalarıyla, yaşlı denizcilerle konuştum. Defter doldu.',
                            'Belki bir gün bu defter küçük bir sözlüğe dönüşür. Tuzlu kelimelerin sözlüğü. Denizin dilini, onu konuşan son kuşak tamamen kaybolmadan kayda geçiren bir sözlük. Çünkü bir dil yalnızca konuşanlarıyla yaşar; ama yazıya geçirildiğinde, bir sonraki kuşağa ulaşma şansı bulur.',
                        ],
                    ],
                ],
            ],
            [
                'number' => 2,
                'title' => 'Kıyı - Sayı 2: Yol',
                'days_ago' => 12,
                'editor_note' => 'İkinci sayımızın kelimesi "yol". Yürüyerek, trenle, mektupla… İnsanın bir yerden bir yere, bir insandan bir insana nasıl ulaştığını düşündük. Yolun kendisinin, varılan yerden daha önemli olduğu anları aradık.',
                'articles' => [
                    [
                        'title' => 'Yürümenin Edebiyatı',
                        'author' => 'ece.yilmaz',
                        'category' => 'Deneme',
                        'blocks' => [
                            'Yürümek, insanın en eski ve en basit eylemlerinden biridir. Ama edebiyat tarihine baktığımızda, yürümenin aynı zamanda bir düşünme biçimi, bir yazma yöntemi, hatta bir yaşam felsefesi olduğunu görürüz. Pek çok yazar, en iyi fikirlerinin yürürken geldiğini söylemiştir.',
                            '## Yalnız Gezerin Düşleri',
                            'Jean-Jacques Rousseau, hayatının son yıllarında yazdığı "Yalnız Gezerin Düşleri" adlı kitabında, Paris çevresinde yaptığı yürüyüşleri ve bu yürüyüşlerde aklından geçenleri anlatır. Kitap, her biri bir yürüyüşe karşılık gelen on bölümden oluşur ve son bölüm yarım kalmıştır.',
                            'Rousseau için yürümek, toplumdan uzaklaşmanın, kendi iç dünyasına dönmenin bir yoluydu. Yürürken bitkileri inceliyor, doğayı gözlemliyor, geçmişini düşünüyordu. Bu yürüyüşler, onun için bir tür terapiydi; hayatının çalkantılı dönemlerinden sonra huzur bulmanın yolu.',
                            '## Walden\'dan Yürüyüşe',
                            'Henry David Thoreau, yalnızca Walden Gölü kıyısında yaşadığı yıllarla değil, yürüyüş üzerine yazdığı denemeyle de tanınır. Thoreau, günde en az dört saat ormanlarda ve kırlarda yürümeden sağlığını ve ruh halini koruyamayacağını yazar.',
                            'Thoreau\'nun yürüyüşü, bir yere gitmek için yapılan bir yürüyüş değildir. Amaçsız, planlanmamış, doğanın içinde kaybolmayı göze alan bir yürüyüştür. Ona göre gerçek yürüyüşçü, her an geri dönmemeyi göze alan kişidir.[[dn:Thoreau\'nun denemesi ölümünden kısa süre sonra, 1862\'de yayımlandı. Metin, yürüyüşü doğayla kurulan manevi bir ilişki olarak tanımlayan en etkili metinlerden biri sayılır.]]',
                            '> Yürüyüş, varılacak bir yer için değil, yolun kendisi için yapıldığında, düşünceye dönüşür.',
                            '## Şehirde Yürümek',
                            'Yürümenin edebiyatı yalnızca kırlarla sınırlı değildir. On dokuzuncu yüzyılda Paris\'te "flâneur" adı verilen bir tip ortaya çıktı: şehrin sokaklarında amaçsızca dolaşan, kalabalıkları, vitrinleri, insanları gözlemleyen bir gezgin. Charles Baudelaire, bu figürü şiirinde ve yazılarında ölümsüzleştirdi.',
                            'İsviçreli yazar Robert Walser\'ın "Gezinti" adlı uzun öyküsü, bir yazarın küçük bir kasabada yaptığı bir günlük yürüyüşü anlatır. Öykü boyunca anlatıcı, karşılaştığı insanlarla konuşur, dükkânlara girer, manzaraları seyreder. Basit görünen bu yürüyüş, hayata dair derin bir düşünceye dönüşür.',
                            '## Bizim Yürüyüşlerimiz',
                            'Türk edebiyatında da yürüyüşün izleri vardır. Şehir yazıları, gezi notları, anılar, pek çoğu bir yürüyüşün kaydıdır. Bir sokakta yürürken hatırlanan bir çocukluk anısı, bir çarşıda karşılaşılan eski bir tanıdık, bir sahilde görülen bir manzara.',
                            'Belki de bugün, arabaların, toplu taşımanın, ekranların egemen olduğu bir çağda, yürümek her zamankinden daha değerli. Yürümek, yavaşlamanın, çevremizi fark etmenin, kendi düşüncelerimizi duymanın bir yolu.',
                            'Bu yazıyı okuduktan sonra, bir yürüyüşe çıkmanızı öneriyorum. Bir hedef belirlemeden, bir süre koymadan. Yalnızca yürüyün ve aklınıza neler geldiğini fark edin. Belki siz de yürüyüşün edebiyatına kendi sayfanızı eklersiniz.',
                        ],
                    ],
                    [
                        'title' => 'Tren Penceresinden Anadolu',
                        'author' => 'author',
                        'category' => 'Deneme',
                        'blocks' => [
                            'Uçakla gidilen bir yolculuk, bir yerden kalkıp başka bir yere inmekten ibarettir. Arada kalan her şey, bulutların altında görünmez olur. Trenle gidilen bir yolculuk ise tam tersine, arada kalanın yolculuğudur. Pencereden akan manzara, trenin ritmik sesi, istasyonlarda binip inen yolcular, yolculuğun kendisini bir deneyime dönüştürür.',
                            'Geçen kış Ankara\'dan Kars\'a trenle gittim. Bir gün bir gece süren bu yolculuk boyunca, pencereden Anadolu\'nun değişen yüzünü izledim.',
                            '## Bozkır',
                            'Ankara\'dan çıktıktan sonra tren, uçsuz bucaksız bir bozkıra girer. Kışın bu bozkır, karla kaplı beyaz bir denize dönüşür. Ufka kadar uzanan beyazlığın ortasında yalnızca birkaç köy, birkaç ağaç, bir de telgraf direkleri.',
                            'Bu manzarada insan zamanı unutur. Saatler geçer ama manzara pek değişmez. Trenin sesi, tekerleklerin raylara vuruşunun düzenli ritmi, bir tür meditasyona dönüşür. Kitap okumaya çalışırsınız ama gözünüz sürekli pencereye kayar.',
                            '## İstasyonlar',
                            'Anadolu\'nun küçük istasyonları, kendi başlarına bir dünya. Çoğu yirminci yüzyılın başlarında yapılmış, taş binalar. Önlerinde bir su deposu, bir saat, bir de istasyon şefinin bayrağı. Bazılarında tren yalnızca birkaç dakika durur; bir iki yolcu iner, bir iki yolcu biner.',
                            'Bu istasyonlarda bazen satıcılar trene yaklaşır: simit, çay, peynir, yöresel tatlılar. Pencereden uzanıp bir şeyler almak, bu yolculuğun küçük zevklerinden biri. Bir istasyonda aldığım sıcak çay, soğuk kış gününde bütün yolculuğun en güzel anlarından biri oldu.[[dn:Anadolu\'daki pek çok eski istasyon binası, demiryolu hattının inşa edildiği döneme ait taş yapılardır ve bir kısmı bugün koruma altındadır.]]',
                            '> Tren penceresi, hareket eden bir tablodur. Her an değişir ama hiçbir zaman tekrar etmez.',
                            '## Dağlar',
                            'Erzincan\'dan sonra manzara değişir. Bozkırın düzlüğü yerini dağlara bırakır. Tren, derin vadilerden, tünellerden, köprülerden geçer. Karlı zirveler, donmuş nehirler, çam ormanları. Pencereden bakarken, bu hattı inşa eden insanların ne büyük bir emek harcadığını düşünürsünüz.',
                            'Gece çöktüğünde manzara kaybolur ama yolculuk devam eder. Kompartımanda uyumaya çalışırken, trenin sesi bir ninni gibi gelir. Arada bir, bir istasyonun ışıkları pencereden süzülür ve tekrar karanlık.',
                            '## Yol Arkadaşları',
                            'Trenle yolculuğun belki en güzel yanı, yol arkadaşlarıdır. Uçakta yanınızdaki kişiyle neredeyse hiç konuşmazsınız; trende ise uzun saatler boyunca aynı kompartımanı paylaşırsınız. Sohbetler başlar, hikâyeler anlatılır, yiyecekler paylaşılır.',
                            'Bu yolculukta kompartımanımı Kars\'a dönen emekli bir öğretmenle, ailesini ziyarete giden bir üniversite öğrencisiyle ve bir fotoğrafçıyla paylaştım. Emekli öğretmen, gençliğinde bu hatta kaç kez yolculuk yaptığını, eskiden trenlerin nasıl olduğunu anlattı. Öğrenci, okulunu ve hayallerini. Fotoğrafçı ise pencereden çektiği kareleri gösterdi.',
                            'Kars\'a vardığımızda sabahın erken saatleriydi. Kar yağıyordu. Birbirimize veda ederken, bir günlük yolculuğun bir ömürlük tanışıklık gibi geldiğini düşündüm. Belki de trenin sırrı budur: insanları, manzaraları ve zamanı aynı pencerede buluşturur.',
                        ],
                    ],
                    [
                        'title' => 'Mektup: Kaybolan Bir Tür mü?',
                        'author' => 'deniz.yalcin',
                        'category' => 'Deneme',
                        'blocks' => [
                            'En son ne zaman elle bir mektup yazdınız? Bir kâğıda, bir kalemle, bir zarfa koyup pul yapıştırarak? Çoğumuz için bu sorunun cevabı ya yıllar öncesidir ya da hiç. Mektup, bir iletişim aracı olarak neredeyse tamamen yerini e-postaya, mesajlaşmaya, sosyal medyaya bıraktı.',
                            'Ama mektup yalnızca bir iletişim aracı değildi. Bir edebi tür, bir düşünme biçimi, bir ilişki kurma yoluydu. Mektubun kaybolmasıyla birlikte, bu değerlerin de kaybolup kaybolmadığını düşünmek istiyorum.',
                            '## Mektubun Zamanı',
                            'Mektubu mesajdan ayıran en önemli şey, zamandır. Bir mektup yazılır, postaya verilir, günler ya da haftalar sonra ulaşır, okunur, cevabı yazılır ve yine günler ya da haftalar sonra geri döner. Bu bekleyiş, mektubun doğasının bir parçasıdır.',
                            'Bu bekleyiş, mektubun içeriğini de biçimlendirir. Bir mektup yazan kişi, karşısındakinin cevabını hemen alamayacağını bilir. Bu yüzden daha düşünerek, daha derinlemesine yazar. Anlık tepkiler yerine olgunlaşmış düşünceler, kısa cümleler yerine uzun paragraflar.',
                            '> Mektup, zamanı kâğıda katlamaktır. Yazıldığı an ile okunduğu an arasındaki mesafe, onun anlamının bir parçasıdır.',
                            '## Genç Bir Şaire',
                            'Edebiyat tarihinin en ünlü mektuplarından bazıları, Rainer Maria Rilke\'nin genç bir şaire yazdığı mektuplardır. Rilke, kendisine şiirlerini gönderip görüş isteyen genç bir askerî öğrenciye birkaç yıl boyunca mektuplar yazmış; bu mektuplar Rilke\'nin ölümünden sonra kitap olarak yayımlanmıştır.[[dn:Mektuplar, alıcıları Franz Xaver Kappus tarafından Rilke\'nin ölümünden birkaç yıl sonra, 1929\'da yayımlandı ve kısa sürede pek çok dile çevrildi.]]',
                            'Rilke bu mektuplarda genç şaire nasıl şiir yazılacağını değil, nasıl yaşanacağını anlatır. Yalnızlığı kabul etmeyi, soruları sevmeyi, sabırlı olmayı öğütler. Bu mektuplar, yüz yılı aşkın bir süre sonra hâlâ okunuyor, çünkü içlerindeki düşünceler zamansızdır.',
                            'Böyle bir metin, bir mesajlaşma uygulamasında yazılabilir miydi? Belki. Ama mektubun ağırbaşlılığı, yavaşlığı, yazarı ile okuru arasındaki mesafe, bu metinlerin derinliğine katkıda bulunmuştur.',
                            '## Mektubun Maddiliği',
                            'Elle yazılmış bir mektup, aynı zamanda bir nesnedir. Kâğıdın dokusu, mürekkebin rengi, el yazısının kendine özgü eğimi, bazen bir leke, bazen bir silinti. Bu maddilik, mektuba bir kişilik katar. Bir e-postayı saklarız belki, ama bir mektubu bir kutuda, bir çekmecede, bir kitabın arasında saklarız.',
                            'Eski mektupları okumak, geçmişle kurulan en dokunaklı bağlardan biridir. Bir büyükannenin gençliğinde yazdığı bir mektup, bir askerin cepheden gönderdiği bir not, iki sevgilinin yıllar boyunca yazıştığı mektuplar. Bu mektuplar, yalnızca yazıldıkları dönemin tarihini değil, yazanların iç dünyasını da taşır.',
                            '## Yeniden Yazmak',
                            'Mektup kaybolan bir tür mü? Belki gündelik iletişimde öyle. Ama mektubun bize öğrettiği şeyler, yavaşlık, derinlik, özen, kaybolmak zorunda değil.',
                            'Size bir öneri: Bu ay, sevdiğiniz birine elle bir mektup yazın. Uzun olmasına gerek yok. Bir sayfa, belki yarım sayfa. Ama düşünerek, özenle yazın. Zarfa koyun, pul yapıştırın, postaya verin. Ve cevabını beklemenin tadını çıkarın.',
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'name' => 'Düşünce Atlası',
        'description' => 'Felsefe, bilim tarihi ve dil üzerine üç ayda bir yayımlanan bir dergi. Büyük soruları küçük hikâyelerle anlatmayı dener.',
        'issues' => [
            [
                'number' => 1,
                'title' => 'Düşünce Atlası - Sayı 1: Zaman',
                'days_ago' => 45,
                'editor_note' => 'Zaman, hepimizin her an içinde yaşadığı ama tanımlamakta en çok zorlandığımız şeylerden biri. Bu sayıda zamanı iki yönden ele alıyoruz: saatlerin ve takvimlerin ölçtüğü toplumsal zaman ile içimizde akan, ölçülmeye direnen yaşanan zaman.',
                'articles' => [
                    [
                        'title' => 'Saatin İcadı ve Zamanın Disiplini',
                        'author' => 'author',
                        'category' => 'Tarih',
                        'blocks' => [
                            'Bugün hayatımızın neredeyse her anı saatle düzenleniyor. İşe saat dokuzda başlıyor, öğle yemeğini on ikide yiyor, trene yedi kırk beşte biniyoruz. Saati bu kadar doğal kabul ediyoruz ki onun olmadığı bir dünyayı hayal etmek zor. Oysa insanlık tarihinin büyük bölümünde zaman, saatle değil, güneşle, mevsimlerle, çan sesleriyle ölçüldü.',
                            '## Güneşin Saati',
                            'Mekanik saatlerden önce zamanı ölçmenin çeşitli yolları vardı: güneş saatleri, su saatleri, kum saatleri, mum saatleri. Ama bu araçların hiçbiri gündelik hayatı dakikası dakikasına düzenleyecek kadar hassas değildi. İnsanlar zamanı daha çok doğal olaylarla ölçüyordu: güneşin doğuşu, öğle vakti, güneşin batışı.',
                            'İslam dünyasında namaz vakitlerinin belirlenmesi, zaman ölçümünü önemli bir bilimsel uğraş haline getirdi. Osmanlı şehirlerinde büyük camilerin yanında muvakkithaneler bulunurdu; burada görevli muvakkitler, gök cisimlerinin hareketlerini gözlemleyerek namaz vakitlerini hesaplardı.[[dn:Muvakkithaneler aynı zamanda şehrin saat ayarlama merkezleriydi; halk saatlerini buradaki saatlere göre ayarlardı.]]',
                            '## Mekanik Saatin Doğuşu',
                            'Ağırlıkla çalışan ilk mekanik saatler, on üçüncü yüzyılın sonlarında Avrupa\'da ortaya çıktı. Bu saatler başlangıçta büyük, kaba ve pek hassas değildi; genellikle kilise kulelerine ya da belediye binalarına yerleştiriliyordu. Göstergeleri bile yoktu çoğu zaman; saati yalnızca çan sesleriyle bildiriyorlardı.',
                            'Zamanla saatler küçüldü, hassaslaştı ve yaygınlaştı. On yedinci yüzyılda sarkaçlı saatin icadı, zaman ölçümünde büyük bir sıçrama yarattı. Artık dakikaları, hatta saniyeleri ölçmek mümkündü.',
                            '> Saat, zamanı ölçmekle kalmadı; zamanın ne olduğunu da değiştirdi. Akan bir nehir olan zaman, eşit parçalara bölünmüş bir cetvele dönüştü.',
                            '## Fabrika Düdüğü',
                            'İngiliz tarihçi E. P. Thompson, 1967\'de yayımladığı ünlü makalesinde, sanayi devriminin insanların zamanla ilişkisini nasıl değiştirdiğini anlatır. Thompson\'a göre sanayi öncesi toplumlarda iş, göreve göre düzenlenirdi: hasat zamanı gece gündüz çalışılır, kış aylarında daha az çalışılırdı. Sanayi toplumunda ise iş, saate göre düzenlendi.',
                            'Fabrikalar, işçilerin belirli saatlerde gelip belirli saatlerde çıkmasını, mesai saatleri boyunca kesintisiz çalışmasını gerektiriyordu. Fabrika düdüğü, zaman disiplininin sesi oldu. Geç kalmak cezalandırıldı, dakiklik bir erdem haline getirildi.',
                            '## Demiryolu Saati',
                            'Zaman disiplininin bir başka büyük dönüm noktası, demiryollarıydı. Demiryollarından önce her şehir kendi yerel saatini kullanıyordu; öğle vakti, güneşin en tepeye çıktığı andı ve bu an şehirden şehre birkaç dakika farklıydı.',
                            'Trenlerin tarifelere göre işlemesi için tek bir standart zaman gerekiyordu. İngiltere\'de demiryolu şirketleri on dokuzuncu yüzyılın ortalarında ortak bir demiryolu saati kullanmaya başladı. 1884\'te Washington\'da toplanan uluslararası bir konferansta Greenwich başlangıç meridyeni olarak kabul edildi; bu karar, bugünkü saat dilimleri sisteminin temelini oluşturdu.',
                            'Bugün cep telefonlarımızdaki saatler, uydularla senkronize ediliyor ve saniyenin binde biri hassasiyetle çalışıyor. Ama belki de bu hassasiyetin ortasında, güneşin doğuşunu ve batışını, mevsimlerin dönüşünü, doğal zamanın ritmini hatırlamak, hiç olmadığı kadar önemli.',
                        ],
                    ],
                    [
                        'title' => 'Bergson ve Yaşanan Zaman',
                        'author' => 'deniz.yalcin',
                        'category' => 'Felsefe',
                        'blocks' => [
                            'Bir bekleme salonunda geçen on dakika ile sevdiğiniz biriyle geçen on dakika aynı uzunlukta mıdır? Saate göre evet. Ama yaşadığımız deneyime göre kesinlikle hayır. Bekleme salonundaki on dakika bitmek bilmez, sevdiğimizle geçen on dakika göz açıp kapayıncaya kadar geçer.',
                            'Fransız filozof Henri Bergson, felsefesinin önemli bir bölümünü bu farkı düşünmeye adadı. Ona göre saatin ölçtüğü zaman ile bizim yaşadığımız zaman, birbirinden temelden farklı iki şeydi.',
                            '## Süre',
                            'Bergson, 1889\'da yayımlanan ilk büyük eserinde, zamanın iki farklı kavranışını ayırt eder. Birincisi, bilimin ve saatin zamanıdır: homojen, ölçülebilir, eşit birimlere bölünebilir bir zaman. Bergson\'a göre bu zaman aslında uzaydan ödünç alınmış bir kavramdır; zamanı bir çizgi gibi, yan yana dizilmiş noktalar gibi düşünürüz.',
                            'İkincisi ise Bergson\'un "süre" adını verdiği yaşanan zamandır. Süre, bilinçte akan, bölünemeyen, her anın bir öncekini içinde taşıdığı bir akıştır. Bir melodiyi dinlerken notaları tek tek değil, bir bütün olarak duyarız; her nota, önceki notaların yankısını taşır. Süre de böyledir.[[dn:Bergson\'un kullandığı Fransızca "durée" kelimesi Türkçeye genellikle "süre" ya da "süreklilik" olarak çevrilir.]]',
                            '> Saat zamanı bölerek ölçer; ama yaşanan zaman bölünemez. Onu bölmeye çalıştığımızda, artık yaşanan zamanı değil, onun bir haritasını elimizde tutarız.',
                            '## Özgürlük',
                            'Bergson için bu ayrım yalnızca kuramsal bir mesele değildi; özgürlük sorunuyla doğrudan bağlantılıydı. Eğer zamanı yalnızca ölçülebilir, önceden belirlenebilir anlar dizisi olarak düşünürsek, eylemlerimiz de önceden belirlenmiş gibi görünür. Ama süre içinde yaşayan bilinç, her an yeni bir şey yaratır; geçmişin tamamını taşıyarak geleceğe açılır.',
                            'Bu yüzden Bergson\'a göre özgür eylem, bütün kişiliğimizin, bütün geçmişimizin içinden fışkıran eylemdir. Önceden hesaplanamaz, çünkü süre her an yenidir.',
                            '## Einstein ile Karşılaşma',
                            'Bergson\'un felsefesi, yirminci yüzyılın başında büyük bir etki yarattı. Dersleri kalabalıklar tarafından izlendi, kitapları pek çok dile çevrildi, 1927\'de Nobel Edebiyat Ödülü\'ne layık görüldü.',
                            'Ama 1922\'de Paris\'te Albert Einstein ile yaptığı bir tartışma, Bergson\'un itibarını sarstı. Bergson, görelilik kuramının zamanla ilgili bazı yorumlarını eleştirdi ve yaşanan zamanın fiziğin zamanına indirgenemeyeceğini savundu. Einstein ise filozofların zamanının diye bir şey olmadığını, yalnızca psikolojik bir zaman ile fiziksel bir zaman olduğunu söyledi.',
                            'Bu tartışmada kimin haklı olduğu hâlâ tartışılıyor. Fizikçilerin çoğu Einstein\'ın tarafını tuttu; ama bazı filozoflar ve bilim tarihçileri, Bergson\'un sorduğu soruların hâlâ önemli olduğunu düşünüyor. Yaşanan zamanın deneyimi, fiziğin denklemlerinde yer almıyor ama bizim için gerçek.',
                            '## Bugün Bergson',
                            'Bugün, her anımızın saatle, takvimle, bildirimle bölündüğü bir çağda, Bergson\'un süre kavramı yeniden anlam kazanıyor. Hep koşturan, hep bir sonraki ana yetişmeye çalışan bir hayatta, yaşanan zamanın derinliğini kaybediyoruz.',
                            'Belki Bergson\'u okumanın en iyi yolu, onun felsefesini yaşamaktır: bir melodiyi baştan sona dikkatle dinlemek, bir yürüyüşü saate bakmadan yapmak, bir sohbetin ne kadar sürdüğünü önemsemeden içine dalmak. O zaman saatin zamanı ile yaşanan zaman arasındaki farkı, kitaplardan değil, kendi deneyimimizden öğreniriz.',
                        ],
                    ],
                ],
            ],
            [
                'number' => 2,
                'title' => 'Düşünce Atlası - Sayı 2: Dil',
                'days_ago' => 6,
                'editor_note' => 'Bu sayının konusu dil. Kelimelerin diller arasında nasıl göç ettiğini ve konuştuğumuz dilin dünyayı görme biçimimizi ne ölçüde etkilediğini tartışıyoruz. İki yazı da aynı soruya farklı yönlerden yaklaşıyor: Dil bir araç mı, yoksa içinde yaşadığımız bir ev mi?',
                'articles' => [
                    [
                        'title' => 'Kelimelerin Göçü',
                        'author' => 'orhan.demir',
                        'category' => 'Tarih',
                        'blocks' => [
                            'Kelimeler de insanlar gibi göç eder. Bir dilden ötekine geçer, yeni bir ülkeye yerleşir, zamanla orada yerli sayılır hale gelir. Bir kelimenin geçmişini araştırmak, çoğu zaman bir halkın ticaretini, savaşlarını, komşuluklarını ve kültürel alışverişini araştırmak demektir.',
                            'Türkçe, bu göçlerin en zengin tanıklarından biridir. Orta Asya\'dan Anadolu\'ya uzanan uzun tarihi boyunca Türkçe, pek çok dille temas etti ve bu dillerden binlerce kelime aldı. Aynı zamanda kendi kelimelerini de başka dillere verdi.',
                            '## Doğudan Gelenler',
                            'Türkçenin en çok kelime aldığı diller Arapça ve Farsçadır. İslamiyetin kabulünden sonra din, bilim, hukuk ve edebiyat alanlarında pek çok Arapça kelime Türkçeye girdi. Farsça ise özellikle edebiyat ve saray dili üzerinden etkili oldu.',
                            'Bugün gündelik konuşmada kullandığımız pek çok kelime, bu köklerden gelir: kitap, kalem, dünya, hayat, zaman, insan, akıl, fikir Arapçadan; hafta, pazar, çarşı, şehir, dost Farsçadan. Bu kelimeler o kadar yerleşmiştir ki çoğumuz onların başka bir dilden geldiğini fark etmeyiz bile.',
                            '## Batıdan Gelenler',
                            'On dokuzuncu yüzyılda Osmanlı\'nın Avrupa ile ilişkilerinin yoğunlaşmasıyla birlikte, Fransızca kelimeler Türkçeye girmeye başladı. Özellikle modern kurumlar, teknolojiler ve yaşam biçimleriyle ilgili kelimeler: otobüs, asansör, tren, sinema, tiyatro, kuaför, pantolon, kravat.',
                            'İtalyancadan ise daha erken dönemlerde, özellikle denizcilik ve ticaret yoluyla kelimeler geldi. Banka, fatura, lokanta, liste, fırtına ve daha pek çoğu.[[dn:"Lokanta" kelimesi İtalyanca "locanda"dan, yani han, konaklama yeri anlamındaki bir kelimeden gelir; Türkçede zamanla yemek yenen yer anlamına kaymıştır.]] Rumcadan ise liman, fener, kiremit gibi kelimeler Türkçeye geçti.',
                            '> Bir dilin sözlüğü, o dili konuşan halkın komşularının listesidir.',
                            '## Batıya Gidenler',
                            'Göç tek yönlü değildir. Türkçe de pek çok dile kelime verdi. Yoğurt, pek çok Avrupa dilinde Türkçedeki adıyla bilinir. Köşk, Fransızcaya ve İngilizceye "kiosque" ve "kiosk" olarak geçti ve anlamı zamanla küçük bir satış kulübesine dönüştü. Divan, hem bir mobilya hem bir meclis anlamında Avrupa dillerine girdi.',
                            'Balkan dillerinde ise Türkçe kelimeler çok daha yoğundur. Sırpça, Bulgarca, Boşnakça, Arnavutça ve Yunancada yüzlerce Türkçe kökenli kelime yaşar; bunların çoğu mutfak, ev eşyaları, zanaatlar ve gündelik hayatla ilgilidir.',
                            '## Dil Devrimi',
                            'Yirminci yüzyılda Türkçe, bilinçli bir sadeleşme sürecinden geçti. 1932\'de kurulan Türk Dili Tetkik Cemiyeti, bugünkü Türk Dil Kurumu\'nun temelini oluşturdu. Amaç, Türkçeyi yabancı kelimelerden arındırmak ve yeni kavramlar için Türkçe kökenli kelimeler türetmekti.',
                            'Bu süreçte pek çok yeni kelime türetildi: okul, öğrenci, öğretmen, uçak, yüzyıl, bilim, sözlük. Bazı yeni kelimeler kolayca benimsendi, bazıları tutmadı. Bazı eski kelimeler kayboldu, bazıları yeni kelimelerle yan yana yaşamaya devam etti.',
                            'Bugün Türkçe konuşurken, bu uzun göç tarihinin bütün katmanlarını kullanıyoruz. Bir cümlede Arapça, Farsça, Fransızca ve Türkçe kökenli kelimeler yan yana gelebiliyor. Bu karışım, bir zayıflık değil, bir zenginliktir. Çünkü her kelime, bir yolculuğun hikâyesini taşır.',
                        ],
                    ],
                    [
                        'title' => 'Dil Düşünceyi Biçimler mi?',
                        'author' => 'deniz.yalcin',
                        'category' => 'Felsefe',
                        'blocks' => [
                            'Farklı diller konuşan insanlar, dünyayı farklı mı görür? Bu soru, dilbilimciler, psikologlar ve filozoflar arasında yüz yılı aşkın bir süredir tartışılıyor. Cevabı da hâlâ kesin değil. Ama tartışmanın kendisi, dilin ne olduğuna dair bize çok şey öğretiyor.',
                            '## Sapir ve Whorf',
                            'Yirminci yüzyılın ilk yarısında Amerikalı dilbilimciler Edward Sapir ve Benjamin Lee Whorf, bugün onların adıyla anılan bir hipotez geliştirdiler. Bu hipoteze göre konuştuğumuz dil, düşünme biçimimizi belirler ya da en azından etkiler.',
                            'Whorf, Kızılderili dilleri üzerine yaptığı çalışmalarda, bazı dillerin zamanı, nesneleri ve olayları Avrupa dillerinden çok farklı biçimde kategorize ettiğini öne sürdü. Ona göre bu farklılıklar, o dilleri konuşan insanların dünyayı farklı algılamasına yol açıyordu.',
                            'Hipotezin güçlü biçimi, yani dilin düşünceyi tamamen belirlediği görüşü, bugün pek kabul görmüyor. Ama zayıf biçimi, yani dilin düşünceyi bazı alanlarda etkileyebileceği görüşü, hâlâ araştırılıyor.[[dn:Whorf\'un bazı iddiaları, özellikle belirli dillerin zaman kavramına ilişkin olanları, sonraki araştırmacılar tarafından ciddi biçimde eleştirilmiştir.]]',
                            '## Renklerin Dili',
                            'Dilin düşünceyi etkileyip etkilemediğini araştırmanın en verimli alanlarından biri renklerdir. Farklı diller, renk yelpazesini farklı biçimlerde böler. Bazı dillerde yalnızca birkaç temel renk kelimesi varken, bazılarında on ya da daha fazla temel renk kelimesi bulunur.',
                            '1969\'da Brent Berlin ve Paul Kay, pek çok dildeki temel renk kelimelerini inceleyen bir çalışma yayımladılar. Vardıkları sonuç, renk kelimelerinin rastgele değil, belirli bir düzen içinde geliştiğiydi. Bu bulgu, dillerin renkleri tamamen keyfi biçimde bölmediğini, insan algısının ortak özelliklerinin de rol oynadığını gösteriyordu.',
                            'Daha sonraki bazı deneyler, açık mavi ile koyu mavi için ayrı temel kelimeleri olan dillerin konuşucularının, bu iki rengi biraz daha hızlı ayırt edebildiğini gösterdi. Fark küçüktü ama ölçülebilirdi. Dil, algıyı belirlemiyordu belki ama onu hafifçe yönlendirebiliyordu.',
                            '> Dil bir gözlük değil belki, ama bir el feneri. Neye ışık tuttuğumuzu, neyi karanlıkta bıraktığımızı etkiler.',
                            '## Yönlerin Dili',
                            'Bir başka ilginç örnek, yön kavramıdır. Türkçede olduğu gibi pek çok dilde yönleri kendi bedenimize göre anlatırız: sağ, sol, ön, arka. Ama bazı dillerde yönler her zaman mutlak olarak ifade edilir: kuzey, güney, doğu, batı. Bu dillerin konuşucuları "bardağı soluna koy" yerine "bardağı kuzeyine koy" der.',
                            'Bu dilleri konuşan insanlar üzerine yapılan araştırmalar, onların her an hangi yöne baktıklarını çok iyi bildiklerini gösteriyor. Dil onları sürekli yön bilgisini takip etmeye zorluyor ve bu, zamanla güçlü bir yön duygusuna dönüşüyor.',
                            '## Türkçe ve Biz',
                            'Peki Türkçe bizim düşünme biçimimizi nasıl etkiliyor? Türkçenin bazı özellikleri bu açıdan ilginç. Örneğin Türkçede bir olayı anlatırken onu doğrudan mı gördüğümüzü yoksa başkasından mı duyduğumuzu fiil ekiyle belirtiriz: "geldi" ile "gelmiş" arasındaki fark. Bu, konuşucuyu bilginin kaynağına dikkat etmeye yönlendirir.',
                            'Bu tür özellikler, düşünceyi belirlemez belki. Ama dilin, dünyayla kurduğumuz ilişkinin ayrılmaz bir parçası olduğunu hatırlatır. Dil, düşüncenin kabı değil, düşünceyle birlikte büyüyen, onu besleyen ve ondan beslenen canlı bir yapıdır.',
                        ],
                    ],
                ],
            ],
        ],
    ],
];
