<?php

/*
 * Demo içerik — "İstanbul Defterleri" (Orhan Demir, tarih / deneme). LibraryDemoSeeder okur.
 * Blok sözdizimi: "## " ara başlık, "> " alıntı, "---" süs ayırıcı, [[dn:…]] dipnot.
 */

return [
    'preface' => [
        'Bu defterler yıllar içinde, İstanbul\'un farklı semtlerinde yürürken, iskelelerde vapur beklerken, kahvehanelerde çay içerken tuttuğum notlardan doğdu. Bir tarih kitabı yazma iddiam yok; tarihçiler bu şehri benden çok daha iyi anlattılar. Benim yapmak istediğim, bir şehrin gündelik hayatına, sokaklarının, iskelelerinin, çarşılarının diline kulak vermek.',
        'Her bölüm bir mekândan yola çıkıyor ama zamanda ileri geri gidiyor. Çünkü İstanbul\'da hiçbir mekân tek bir zamana ait değil; aynı sokakta Bizans\'ın taşı, Osmanlı\'nın ahşabı ve bugünün betonu yan yana duruyor.',
    ],
    [
        'title' => 'Galata\'dan Bakmak',
        'blocks' => [
            'İstanbul\'u anlamak isteyen herkese önce yüksek bir yerden bakmasını öneririm. Şehrin haritası sokaklarda kaybolur; tepeden bakınca ise yedi tepenin, iki kıtanın ve üç suyun nasıl bir araya geldiği bir anda görünür. Bunun için benim en sevdiğim yer, bütün turist kalabalığına rağmen, Galata Kulesi\'dir.',
            'Kule, bugünkü haliyle, 1348 yılında Cenevizliler tarafından inşa edildi. O zamanlar Galata, Bizans\'ın izniyle Cenevizli tüccarların yaşadığı surlarla çevrili bir kolonidir ve kule, bu surların en yüksek noktasıdır.[[dn:Cenevizliler kuleye "Christea Turris", yani İsa Kulesi adını vermişti. Kulenin yerinde daha önce ahşap bir Bizans kulesi bulunduğu da aktarılır.]] Liman ve Haliç\'in ağzı buradan kontrol edilir, gelen gemiler gözetlenir.',
            'Fetihten sonra kule farklı işlevler üstlenir: bir dönem zindan, bir dönem gözetleme kulesi, bir dönem de yangın kulesi olur. Ahşap evlerden oluşan bir şehir için yangın kulesi hayati bir görevdir; kulenin tepesindeki bekçi, şehrin herhangi bir yerinde duman gördüğünde işaret verir ve tulumbacılar yola çıkar.',
            '## Hezarfen\'in Kanatları',
            'Galata Kulesi\'nin en ünlü hikâyesi ise bir uçuş hikâyesidir. Evliya Çelebi, Seyahatname\'sinde Hezarfen Ahmed Çelebi adında bir bilginin kendi yaptığı kanatlarla kulenin tepesinden atlayıp Boğaz\'ı geçerek Üsküdar\'a indiğini anlatır.',
            'Bu hikâyenin ne kadarının gerçek olduğu tartışmalıdır. Evliya Çelebi, abartmayı seven, hikâyeyi süslemekten hoşlanan bir anlatıcıdır ve olayı anlatan başka bir çağdaş kaynak bilinmez. Ama hikâyenin kendisi, gerçek olsun ya da olmasın, İstanbul\'un hayal gücünde kalıcı bir yer edinmiştir.',
            '> Bir şehrin efsaneleri, belgelerinden daha çok şey anlatır bazen. Çünkü efsane, o şehrin insanlarının neyi hayal ettiğini gösterir.',
            '## Kulenin Tepesinden',
            'Bugün kulenin seyir terasına çıktığınızda gördüğünüz manzara, Evliya Çelebi\'nin gördüğünden çok farklı olsa da temel hatları aynıdır. Güneyde Haliç\'in ağzı ve karşısında Tarihi Yarımada: Süleymaniye\'nin kubbeleri, Yeni Cami, uzakta Ayasofya ve Sultanahmet\'in minareleri. Doğuda Boğaz\'ın girişi ve karşı kıyıda Üsküdar. Kuzeyde ise Beyoğlu\'nun kalabalık çatıları.',
            'Bu manzaraya bakarken bir şey dikkatimi çeker her seferinde: su. İstanbul bir kara şehri değil, bir su şehridir. Haliç, Boğaz ve Marmara; şehri hem böler hem birleştirir. Bu yüzden İstanbul\'un tarihi, bir anlamda iskelelerin ve teknelerin tarihidir.',
            'Kuleden inip Karaköy\'e doğru yürürken bu düşünceyle, bir sonraki durağımı belirledim: iskeleler.',
        ],
    ],
    [
        'title' => 'Vapur İskeleleri',
        'blocks' => [
            'İstanbul\'da bir iskelede vapur beklemek, şehrin ritmine uyum sağlamanın en iyi yoludur. Burada acele etmek işe yaramaz; vapur saatinde gelir, saatinde gider. Arada geçen zaman, çay içmek, simit yemek, martıları seyretmek içindir.',
            'Vapurlar, İstanbul\'un simgelerinden biri haline gelmeden önce, şehrin iki yakası arasındaki ulaşım kayıklarla sağlanırdı. Pazar kayıkları, piyadeler, saltanat kayıkları… On dokuzuncu yüzyılın ilk yarısında buharlı gemiler ortaya çıkınca bu tablo yavaş yavaş değişmeye başladı.',
            '## Şirket-i Hayriye',
            'Boğaz\'da düzenli vapur seferlerinin kurumsal başlangıcı 1851\'dir. Bu yıl, Boğaziçi\'nde vapur işletmek üzere Şirket-i Hayriye kurulur.[[dn:Şirket-i Hayriye, "hayırlı şirket" anlamına gelir. Osmanlı\'da hisse senedi çıkaran ilk anonim şirketlerden biri olarak da anılır.]] Şirket, kısa sürede Boğaz\'ın iki yakasındaki köyleri birbirine ve şehir merkezine bağlayan bir ağ kurar.',
            'Vapurların gelişiyle Boğaz köylerinin hayatı değişir. Daha önce yalnızca yazlık olarak kullanılan yalılar, artık yıl boyu oturulabilir hale gelir. Memurlar, tüccarlar, sanatkârlar sabah vapuruyla şehre inip akşam vapuruyla evlerine döner. Boğaz, bir sayfiye yeri olmaktan çıkıp şehrin bir parçası olur.',
            'Şirket-i Hayriye\'nin bir yeniliği daha vardır: araba vapuru. 1872\'de hizmete giren Suhulet adlı vapur, atlı arabaları Kabataş ile Üsküdar arasında taşıyabilecek biçimde tasarlanmıştır ve sıkça dünyanın ilk araba vapurlarından biri olarak anılır.',
            '## İskele Hayatı',
            'Eski iskele binaları, çoğu ahşap ya da kagir, kendilerine özgü bir mimari taşır: bekleme salonu, bilet gişesi, kahvehane ve iskele binasının cephesindeki saat. Bazıları bugün hâlâ ayakta; Kanlıca, Emirgân, Anadolu Hisarı iskeleleri gibi.',
            'Benim en sevdiğim iskele sahnesi, akşamüstü, işten dönüş saatinde yaşanır. Vapur iskeleye yanaşırken gemici halatı fırlatır, iskele memuru halatı babaya dolar, iskele tahtası indirilir. Yolcular önce yavaş, sonra hızlanarak iner. Aynı anda bekleyenler binmeye hazırlanır. Bütün bu sahne birkaç dakika sürer ve neredeyse bir koreografi gibi kusursuzdur.',
            '> İstanbul\'da vapura binmek, şehirden bir an için çıkmaktır. Karadaki bütün telaş iskelede kalır; vapurda yalnızca su, martı ve çay vardır.',
            '## Martılar',
            'Vapurdan söz edip martılardan söz etmemek olmaz. Vapurun arkasından uçan, yolcuların attığı simit parçalarını havada kapan martılar, İstanbul\'un en tanıdık görüntülerinden biridir. Martılar, şehrin sesinin de bir parçasıdır; sabahın erken saatlerinde çatılardan gelen çığlıkları, İstanbul\'da uyanan herkesin tanıdığı bir sestir.',
            'Bazı yolcular martıları besler, bazıları onlardan rahatsız olur. Ama İstanbul\'da martısız bir vapur yolculuğu düşünmek zordur. Martılar, vapurla birlikte, suyun şehre ait olduğunu hatırlatan canlı bir işarettir.',
        ],
    ],
    [
        'title' => 'Kahvehaneler ve Sohbet',
        'blocks' => [
            'İstanbul\'da kahvenin hikâyesi, on altıncı yüzyılın ortasında başlar. Tarihçi İbrahim Peçevi\'nin aktardığına göre, 1554 yılında Halepli Hakem ve Şamlı Şems adında iki kişi, Tahtakale\'de şehrin ilk kahvehanesini açar.[[dn:Kaynaklarda bu tarih zaman zaman 1555 olarak da geçer. Peçevi, olayı kendi zamanından yaklaşık yarım yüzyıl önceye tarihleyerek anlatır.]] Kahvehane kısa sürede büyük ilgi görür; okumuşlar, şairler, tüccarlar burada toplanır, sohbet eder, satranç ve tavla oynar.',
            'Kahvehaneler hızla çoğalır. On yedinci yüzyıla gelindiğinde şehrin her semtinde, hatta her mahallesinde bir kahvehane vardır. Bu mekânlar yalnızca kahve içilen yerler değil, haberlerin konuşulduğu, fikirlerin tartışıldığı, şiirlerin okunduğu toplumsal merkezlerdir.',
            '## Yasaklar',
            'Kahvehanelerin bu toplumsal gücü, zaman zaman yönetimin dikkatini çeker. Kahvehanelerde siyasi eleştirilerin konuşulması, dedikoduların yayılması, bazı çevreler tarafından tehlikeli bulunur. On yedinci yüzyılda IV. Murad, kahve ve tütün içilmesini yasaklar ve kahvehaneleri kapattırır.',
            'Ama yasaklar uzun sürmez. Kahve, İstanbul hayatına o kadar yerleşmiştir ki onu yok etmek mümkün olmaz. Kahvehaneler yeniden açılır, yeniden çoğalır ve şehrin gündelik hayatının vazgeçilmez bir parçası olmaya devam eder.',
            '## Meddahlar ve Semai Kahveleri',
            'Kahvehanelerin kültürel hayattaki yeri özellikle on dokuzuncu yüzyılda belirginleşir. Meddahlar, elinde bir mendil ve bir sopayla, kahvehane müşterilerine hikâyeler anlatır; farklı karakterlerin seslerini taklit eder, dinleyicileri güldürür, düşündürür.',
            'Semai kahveleri ise âşıkların saz eşliğinde türküler, destanlar, karşılıklı atışmalar söylediği mekânlardır. Özellikle Ramazan gecelerinde bu kahveler dolup taşar.[[dn:Semai kahvelerinde âşık fasılları, Ramazan\'ın on beşinden sonra başlayıp bayrama kadar sürerdi; kahveciler bu geceler için âşıkları önceden anlaşarak getirirdi.]]',
            '## Bugünün Kahvehaneleri',
            'Bugün İstanbul\'un kahvehaneleri eskisinden çok farklı görünse de temel işlevleri aynı. Mahalle kahvehanelerinde hâlâ emekliler tavla oynuyor, gazeteler okunuyor, günün haberleri tartışılıyor. Sahafların yakınındaki kahvelerde öğrenciler, yazarlar ve okurlar buluşuyor.',
            'Benim en çok sevdiğim, küçük, isimsiz kahvehanelerdir. Birkaç tahta masa, duvarda eski bir saat, ocakta kaynayan çaydanlık ve kahveci, müşterilerinin her birinin çayını nasıl içtiğini bilen biri. Bu kahvehanelerde zaman başka akar. Bir çay bardağının dibi görünene kadar geçen süre, şehrin bütün telaşından daha önemlidir.',
            '> Kahvehane, İstanbul\'un oturma odasıdır. Evlere sığmayan sohbetler burada yapılır.',
            'Ahmet Rasim, on dokuzuncu yüzyılın sonunda yazdığı şehir yazılarında kahvehaneleri sıkça anlatır. Onun gözünde kahvehane, şehrin nabzının tutulduğu yerdir. Bugün de öyle olduğunu düşünüyorum. Bir semti tanımak istiyorsanız, o semtin kahvehanesine gidin ve bir çay isteyin. Gerisi kendiliğinden gelir.',
        ],
    ],
    [
        'title' => 'Yangınlar ve Ahşap Evler',
        'blocks' => [
            'İstanbul\'un eski fotoğraflarına bakarken dikkatimi en çok çeken şey, ahşap evlerin yoğunluğudur. On dokuzuncu yüzyıl sonuna kadar şehrin büyük bölümü ahşaptı: cumbalı evler, dar sokaklar, birbirine yaslanan saçaklar. Bu mimari, şehre benzersiz bir güzellik verirken aynı zamanda büyük bir tehlike de taşıyordu: yangın.',
            '## Yangın Şehri',
            'İstanbul yangınları, şehrin tarihinin ayrılmaz bir parçasıdır. Bir ocaktan sıçrayan kıvılcım, bir mangalın devrilmesi, bir lambanın düşmesi, rüzgârlı bir günde bütün bir mahalleyi küle çevirebilirdi. Evler birbirine o kadar yakındı ki alevler bir çatıdan ötekine kolayca atlıyordu.',
            'Büyük yangınların her biri, şehrin hafızasında bir iz bırakmıştır. 1865 Hocapaşa yangını, bir kahvehaneden çıkıp binlerce binayı yok etmiştir. 1918 Fatih-Cibali yangını, Birinci Dünya Savaşı\'nın son günlerinde, yoksulluk içindeki şehrin binlerce hanesini yakar.[[dn:Yangınlardan sonra yanan alanlar çoğu zaman yeniden ahşap olarak değil, daha geniş ve düzenli sokaklarla, kagir yapılarla imar edilmeye çalışılmıştır. Bu yüzden bugünkü İstanbul\'un pek çok mahallesinin sokak dokusu, yangın sonrası planlamaların izini taşır.]]',
            '## Tulumbacılar',
            'Yangınla mücadelenin en renkli figürleri tulumbacılardır. On sekizinci yüzyılın başında, 1720 civarında, el tulumbası İstanbul\'a gelir ve tulumbacı ocakları kurulur.[[dn:Tulumbanın İstanbul\'a gelişi genellikle Gerçek Davud Ağa adıyla anılan bir kişiye bağlanır.]] Zamanla her mahallenin kendi gönüllü tulumbacı takımı oluşur.',
            'Tulumbacılar, yangın haberi alındığında omuzlarında tulumbayla, yalınayak, bağırarak yangın yerine koşarlardı. Yangını söndürmek kadar, oraya ilk varmak da bir onur meselesiydi. Tulumbacıların kendilerine özgü kıyafetleri, argoları ve türküleri vardı; bu kültür, İstanbul folklorunun unutulmaz bir parçası haline geldi.',
            'Ancak tulumbacılık zamanla bazı sorunlar da yarattı: takımlar arası kavgalar, yangın sahibiyle pazarlık, düzensizlik. Yirminci yüzyılın başında modern itfaiye teşkilatının kurulmasıyla tulumbacı ocakları tarihe karıştı.',
            '## Kalan Evler',
            'Bugün İstanbul\'da ayakta kalmış ahşap evler, bu uzun yangın tarihinin hayatta kalanlarıdır. Kuzguncuk\'ta, Fener ve Balat\'ta, Zeyrek\'te, Arnavutköy\'de hâlâ cumbalı, renkli, eğri büğrü ahşap evler görebilirsiniz. Bazıları özenle restore edilmiş, bazıları bakımsızlıktan çökmek üzere.',
            'Bu evlerin önünden geçerken hep aynı soruyu sorarım kendime: Kaç yangından kurtuldu bu ev? Kaç ailenin hayatı geçti bu cumbanın arkasından? Hangi çocuklar bu merdivenlerde oynadı, hangi kadınlar bu pencerelerden sokağı seyretti?',
            '> Ahşap ev, taş evden farklı yaşlanır. Taş ev ağırbaşlı bir ihtiyar gibidir; ahşap ev ise yaşlandıkça eğilen, kamburlaşan ama hâlâ gülümseyen bir nine.',
            'Ahşap evleri korumak, yalnızca birkaç eski binayı kurtarmak değil, İstanbul\'un bir yaşam biçimini hatırlamaktır. Komşuların pencereden pencereye konuştuğu, sokakta çocukların oynadığı, mahallenin bir aile gibi olduğu bir yaşam biçimi.',
        ],
    ],
    [
        'title' => 'Çarşının Dili',
        'blocks' => [
            'Bir şehrin çarşıları, o şehrin dilini konuşur. İstanbul\'un çarşılarında bu dil, yüzyıllar boyunca biriken ticaret geleneklerinden, esnaf kültüründen ve pazarlık sanatından oluşur.',
            '## Kapalıçarşı',
            'Kapalıçarşı\'nın çekirdeği, fetihten kısa süre sonra, 1455-1461 yılları arasında Fatih Sultan Mehmed\'in emriyle yapılan Cevahir Bedesteni\'dir. Bedesten, değerli malların, mücevherlerin, kumaşların saklandığı ve satıldığı, kalın duvarlı, kapıları geceleri kilitlenen güvenli bir yapıydı.',
            'Zamanla bedestenin çevresine dükkânlar, hanlar ve sokaklar eklenir. Bu sokakların üstü kapatılır ve bugün bildiğimiz Kapalıçarşı ortaya çıkar: binlerce dükkânı, onlarca sokağı, kendi camisi, çeşmesi ve kahvehaneleri olan, adeta bir şehir içinde şehir.[[dn:Kapalıçarşı, tarihi boyunca yangınlar ve depremlerle defalarca hasar görmüş ve yeniden onarılmıştır. Bugünkü yapının önemli bir bölümü, 1894 depreminden sonraki onarımların izini taşır.]]',
            'Kapalıçarşı\'nın sokak adları bile bir tarih anlatır: Kalpakçılar, Yorgancılar, Fesçiler, Sahaflar. Her sokak, bir zamanlar orada toplanan esnafın adını taşır. Bugün o sokaklarda farklı mallar satılsa da isimler kalır; çarşının hafızası isimlerde yaşar.',
            '## Mısır Çarşısı',
            'Eminönü\'ndeki Mısır Çarşısı, Yeni Cami külliyesinin bir parçası olarak on yedinci yüzyılda yapılmıştır. Çarşının adı, Mısır\'dan gelen vergilerle yapıldığı ya da Mısır\'dan gelen baharatların burada satıldığı için verildiği şeklinde açıklanır.',
            'Mısır Çarşısı\'na girdiğinizde sizi ilk karşılayan şey kokudur: tarçın, karanfil, kimyon, pul biber, safran ve kahve. Bu kokular yüzyıllardır aynıdır; çarşının duvarlarına işlemiş gibidir. Baharatçıların önündeki çuvallar, rengârenk tepelerle doludur.',
            '## Pazarlık Sanatı',
            'İstanbul çarşılarında alışveriş, yalnızca para ile mal değişimi değildir; bir sohbettir, bir oyundur, bazen de bir sanattır. Pazarlık, bu sohbetin merkezindedir.',
            'İyi bir pazarlık, iki tarafın da memnun ayrıldığı pazarlıktır. Satıcı malının değerini bilir, alıcı da ne kadar ödemeye razı olduğunu. Arada bir dans gerçekleşir: satıcı fiyatı söyler, alıcı şaşırmış gibi yapar, satıcı malının niteliğini anlatır, alıcı başka dükkânlardan söz eder. Sonunda bir orta yolda buluşulur ve genellikle bir çayla kutlanır.',
            '> Çarşıda "buyurun" demek, "satın alın" demek değildir. "Buyurun", bir sohbete davettir.',
            '## Esnafın Ahlakı',
            'Osmanlı esnaf teşkilatı, ahilik geleneğinden beslenen güçlü bir meslek ahlakına sahipti. Her meslek grubunun kendi kuralları, ustası, kalfası ve çırağı vardı. Kötü mal satan, müşteriyi aldatan esnaf, loncasından uzaklaştırılabilirdi.',
            'Bu geleneğin izleri bugün hâlâ görülebilir. Eski çarşı esnafının bazıları, sabah dükkânını açarken ilk müşteriye "siftah" yapar ve o gün ikinci bir müşteri geldiğinde, henüz siftah yapmamış komşu dükkânı gösterir: "Komşuya buyurun, o daha siftah yapmadı." Bu küçük jest, bir şehrin ticaret hayatının ardındaki dayanışmayı özetler.',
        ],
    ],
    [
        'title' => 'Boğaz\'ın Mevsimleri',
        'blocks' => [
            'Boğaz, her mevsim başka bir yüz gösterir. Aynı kıyı, aynı yalılar, aynı sular; ama ışık, renk ve hava değiştikçe bambaşka bir manzara ortaya çıkar. Bu bölümde, bir yıl boyunca Boğaz kıyısında tuttuğum notları mevsim mevsim aktarmak istiyorum.',
            '## İlkbahar: Erguvan',
            'Nisan ayının ortalarında Boğaz\'ın iki yakası pembeye boyanır. Erguvan ağaçları, yapraklarından önce çiçek açar ve bir haftalığına bütün yamaçları pembe-mor bir örtüyle kaplar.[[dn:Erguvan, eski İstanbul\'da bahar şenliklerinin simgesiydi. Erguvanların açtığı günlerde kıyılarda toplanılıp eğlenceler düzenlendiği aktarılır.]]',
            'Erguvan zamanında Boğaz vapuruna binmek, İstanbul\'un en güzel deneyimlerinden biridir. Kıyılar boyunca uzanan pembe lekeler, yalıların beyaz ve pastel cepheleri, suyun maviliği… Bu manzara, şehrin bütün gürültüsünü bir anda unutturur.',
            '## Yaz: Akıntılar',
            'Yazın Boğaz, hareketin mevsimidir. Kıyılarda balık tutanlar, suya atlayan çocuklar, kayıklar, tekneler, büyük gemiler. Boğaz\'ın güçlü akıntıları, Karadeniz\'den Marmara\'ya doğru akar ve yüzücüler için ciddi bir tehlike oluşturur.',
            'Boğaz\'ın akıntıları iki katmanlıdır: yüzeyde Karadeniz\'in daha az tuzlu suyu güneye, derinde ise Marmara\'nın daha tuzlu ve yoğun suyu kuzeye akar. Balıkçılar bu akıntıları çok iyi bilir; hangi akıntıda hangi balığın yüzdüğünü, hangi mevsimde nerede ağ atılacağını.',
            '## Sonbahar: Göçler',
            'Sonbahar, Boğaz\'da göç mevsimidir. Ağustos sonundan itibaren leylekler ve yırtıcı kuşlar, Avrupa\'dan Afrika\'ya giderken Boğaz\'ın üstünden geçer. Çamlıca Tepesi gibi yüksek noktalardan bakıldığında, gökyüzünde halkalar çizerek yükselen yüzlerce leyleği görmek mümkündür.',
            'Aynı mevsimde denizde de bir göç yaşanır: palamut. Palamut sürüleri Karadeniz\'den Marmara\'ya doğru inerken, Boğaz kıyılarındaki balıkçılar hazırda bekler. Palamut mevsimi, İstanbul mutfağının en önemli dönemlerinden biridir.',
            '> Göç mevsiminde Boğaz, bir geçit olduğunu hatırlar. Kuşlar gökyüzünden, balıklar sudan, hepsi aynı dar yoldan geçer.',
            '## Kış: Poyraz ve Lodos',
            'Kışın Boğaz, rüzgârların mevsimidir. Kuzeyden esen soğuk poyraz, suları dalgalandırır ve kıyıları buzlu bir havayla kaplar. Güneybatıdan esen lodos ise ılık ama şiddetli bir rüzgârdır; dalgaları kıyılara vurdurur, vapur seferlerini aksatır.',
            'Kış günlerinde Boğaz kıyısında yürümek, yazın kalabalığından kaçmak isteyenler için bir sığınaktır. Boş kahvehaneler, kapalı yalıların pancurları, gri gökyüzünün altında gri sular. Bu manzara hüzünlü ama güzeldir; İstanbul\'un en içe dönük yüzüdür.',
        ],
    ],
    [
        'title' => 'Bir Şehri Okumak',
        'blocks' => [
            'Bu defterlerin sonuna gelirken, kendime sık sık sorduğum bir soruyu sizinle paylaşmak istiyorum: Bir şehri okumak ne demektir?',
            'Bir şehri okumak, bir kitabı okumaya benzer ama ondan farklıdır. Kitabın sayfaları sabittir; şehrinki ise her gün değişir. Bir sokak yıkılır, yerine yenisi yapılır. Bir kahvehane kapanır, bir kafe açılır. Bir iskele yenilenir, bir vapur emekliye ayrılır. Şehri okuyan kişi, her seferinde yeni bir baskıyı okur.',
            '## Katmanlar',
            'İstanbul\'u okumak, katmanları okumaktır. Aynı sokakta, bir Bizans sarnıcının üstüne yapılmış bir Osmanlı hanı, onun yanında bir Cumhuriyet dönemi apartmanı, onun karşısında bir cam ve çelik gökdelen. Bu katmanlar birbirini yok etmez; üst üste, yan yana yaşar.',
            'Bu katmanları okumak için özel bir eğitim gerekmez. Yalnızca dikkat gerekir. Bir duvardaki eski taşları fark etmek, bir kapının üstündeki kitabeyi okumaya çalışmak, bir sokağın adının nereden geldiğini merak etmek.',
            '## Şehrin Yazarları',
            'İstanbul\'u benden önce okuyan ve yazan pek çok kişi oldu. Evliya Çelebi\'nin Seyahatname\'si, şehrin on yedinci yüzyıldaki halini bütün renkleriyle anlatır. Ahmet Rasim\'in şehir yazıları, on dokuzuncu yüzyıl sonunun gündelik hayatını yakalar. Reşat Ekrem Koçu\'nun İstanbul Ansiklopedisi ise şehrin bütün tuhaflıklarını, efsanelerini ve unutulmuş hikâyelerini bir araya getirmeye çalışan devasa bir emektir.',
            'Bu yazarları okurken bir şeyi fark ettim: Her biri İstanbul\'u kendi zamanında, kendi gözüyle okumuş ve yazmış. Hiçbiri şehrin tamamını anlatamamış; anlatmaya çalıştıkları şey, şehrin bir parçası, bir anı, bir bakışıdır. Belki de bir şehri okumak, onu hiçbir zaman tam olarak okuyamayacağını kabul etmektir.',
            '> İstanbul bitmeyen bir kitaptır. Her okur ona yeni bir sayfa ekler, ama kitabın sonu hiç gelmez.',
            '## Kendi Defterinizi Tutun',
            'Bu kitabı okuyan herkese bir önerim var: Kendi şehir defterinizi tutun. Yaşadığınız şehir İstanbul olmasa bile. Bir sokakta yürürken gördüğünüz ilginç bir şeyi, bir kahvehanede duyduğunuz bir sohbeti, bir iskelede fark ettiğiniz bir ayrıntıyı not edin.',
            'Zamanla bu notlar, şehrinizin sizin gözünüzden bir portresine dönüşecek. Ve belki bir gün, başka biri o defteri okuyup sizin şehrinizi, sizin zamanınızı, sizin bakışınızı tanıyacak.',
            'Benim defterlerim burada bitiyor. Ama İstanbul\'da yürümeye, iskelelerde vapur beklemeye, kahvehanelerde çay içmeye devam edeceğim. Çünkü şehir, okundukça yazılmaya devam eder.',
        ],
    ],
];
