<?php

/*
 * Demo içerik — "Kıyıda Bir Sabah" (Murat Ekin, roman). LibraryDemoSeeder okur.
 * Blok sözdizimi: "## " ara başlık, "> " alıntı, "---" süs ayırıcı, [[dn:…]] dipnot.
 */

return [
    [
        'title' => 'Dönüş',
        'blocks' => [
            'Otobüs, kasabanın girişindeki zeytinliklerin arasından geçerken Nevin cama yasladığı alnını çekti. On iki yıl olmuştu. On iki yıl boyunca bu yolu yalnızca rüyalarında, bir de anneannesinin her bayram telefonda tekrarladığı cümlede görmüştü: "Zeytinler yine yüklü bu yıl, bir gel de gör."',
            'Gelmemişti. Önce üniversite, sonra İstanbul\'daki atölye, sonra bitmeyen restorasyon işleri. Eski bir konağın tavan göbeğini, bir kilisenin solmuş freskini, bir müzenin çatlak ahşap sandığını onarırken kendi geçmişindeki çatlaklara hiç dokunmamıştı. İnsan başkalarının hasarını onarmaya alışınca kendi evinin çatısının aktığını fark etmiyordu.',
            'Otobüs meydanda durdu. Kapılar tıslayarak açıldığında içeri tuz ve yosun kokusu doldu. Nevin çantasını omzuna aldı, basamaklardan indi ve bir an olduğu yerde kaldı. Meydan küçülmüştü. Çocukken dev gibi görünen çınar şimdi sıradan bir ağaçtı; altındaki kahvehanenin tahta sandalyeleri plastik olmuş, tabelanın harfleri solmuştu. Ama çınarın gölgesi aynı yere düşüyordu ve deniz, sokakların sonunda, her zamanki gibi parlıyordu.',
            'Anneannesinin evi kıyıya inen dar yokuşun sonundaydı. Nevin yürürken ayakkabılarının arnavutkaldırımında çıkardığı sesi dinledi. Bu ses bile tanıdıktı. Kapı önlerinde saksılar, balkonlarda kurumaya asılmış ahtapotlar, bir pencereden taşan radyo sesi… Kasaba, ona hiçbir şey olmamış gibi davranıyordu. Belki de gerçekten hiçbir şey olmamıştı; değişen yalnızca kendisiydi.',
            'Evin mavi kapısının boyası kabarmıştı. Tokmak, bir kadın eli biçimindeki pirinç tokmak, hâlâ yerindeydi. Nevin anahtarı cebinden çıkardı. Notere gittiği gün avukatın uzattığı zarfın içinden çıkan bu anahtar, iki haftadır cebinde bir taş gibi duruyordu. Anneannesi ölmüş, evi ona bırakmıştı. Başka kimseye değil, yalnızca ona.',
            '"Hoş geldin, kızım."',
            'Nevin irkilerek döndü. Karşı evin balkonunda yaşlı bir kadın duruyordu; başında beyaz bir yazma, elinde bir tas dolusu fasulye. Yüzünü hatırlamakta zorlandı, sonra hatırladı: Saniye Teyze. Anneannesinin elli yıllık komşusu, çocukluğunun bütün yaz öğleden sonralarında ona incir reçeli yediren kadın.',
            '"Saniye Teyze… Beni tanıdınız mı?"',
            '"Tanımaz olur muyum? Gözlerin Hayriye\'nin gözleri. Onun gibi de bakıyorsun, bir şey arar gibi." Kadın fasulye tasını balkon demirinin üstüne bıraktı. "Rahmetli her akşam şu kapıya bakardı. Gelir mi diye. Gelmedin."',
            'Cümle bir suçlama gibi değil, bir hava durumu raporu gibi söylenmişti. Nevin yine de yüzünün ısındığını hissetti.',
            '"Gelemedim," dedi. "İşler…"',
            '"Biliyorum, biliyorum. İstanbul büyük, insanı yutar." Saniye Teyze elini salladı. "Anahtar dönmezse biraz yukarı kaldır kapıyı. Yıllardır öyle. Hayriye tamirci çağırmaya kıyamazdı, der ki bu kapı benimle birlikte yaşlandı, huyunu bilirim."',
            'Anahtar gerçekten dönmedi. Nevin kapıyı hafifçe yukarı kaldırdı ve kilit, sanki bir parolayı tanımış gibi, yumuşak bir tıkırtıyla açıldı.',
            '---',
            'İçerisi serindi. Kalın taş duvarlar ağustos sıcağını dışarıda bırakmıştı. Nevin çantasını girişteki sedirin üstüne koydu ve gözlerinin loşluğa alışmasını bekledi. Yavaş yavaş odanın hatları belirdi: pencerenin önündeki dikiş makinesi, duvardaki yuvarlak ayna, köşede üstüne dantel örtü serilmiş ceviz konsol. Konsolun üstünde bir sıra fotoğraf. Nevin yaklaşmadı. Henüz değil.',
            'Mutfağa geçti. Tezgâhın üstünde, ters çevrilmiş bir çay bardağı duruyordu. Yanında bir kavanoz, kapağına mavi kalemle yazılmış: "Ayva, 2023." Anneannesi son reçelini geçen sonbahar yapmıştı demek. Nevin kavanozu eline aldı, ışığa tuttu. Ayva dilimleri koyu kehribar renginde, şeffaf bir şurubun içinde asılı duruyordu. Bir an kavanozu açıp açmamayı düşündü, sonra yerine bıraktı. Bu evdeki her şey bir sözdü sanki; açmak, o sözü bozmak gibi gelecekti.',
            'Arka pencereden bahçe görünüyordu. İncir ağacı, anneannesinin "kraliçe" dediği yaşlı incir, dallarını neredeyse yere kadar sarkıtmıştı. Altındaki taş masada yarım kalmış bir örgü sepeti vardı. Güneş yağmur yememiş, rüzgâr dağıtmamıştı onu. Sanki biri birazdan gelip şişlerini alacak, kaldığı yerden devam edecekti.',
            'Nevin masaya oturdu. İstanbul\'dan çıkarken kendine bir plan yapmıştı: üç gün. Evi toplayacak, emlakçıyla görüşecek, değerli bir şey varsa ayıracak, kalanını bağışlayacaktı. Kasabada anısı olan bir ev, onun hayatına sığmayacak bir yüktü. Bunu kendine defalarca söylemişti.',
            'Şimdi incirin altında otururken planın ne kadar ince bir kâğıttan yapıldığını fark etti. Deniz tarafından esen rüzgâr yaprakları hışırdatıyordu. Uzaktan bir motorun pırpır sesi geliyordu. Ve bahçe duvarının dibinde, anneannesinin her yaz ektiği fesleğenler, kimse sulamadığı halde, inatla yeşeriyordu.',
            'Nevin cebinden telefonunu çıkarıp atölyedeki ortağına kısa bir mesaj yazdı: "Vardım. Birkaç gün uzayabilir." Gönderdikten sonra telefonu ters çevirip masaya bıraktı.',
            'Akşam olurken kıyıya indi. Kasabanın küçük limanında balıkçı tekneleri yan yana dizilmiş, halatları iskele babalarına dolanmıştı. Güneş, karşıdaki adanın arkasına iniyor, suyun üstüne turuncu bir yol çiziyordu. Nevin iskelenin ucuna kadar yürüdü, ayakkabılarını çıkardı ve ayaklarını suya sarkıttı. Su, beklediğinden sıcaktı.',
            'Çocukken tam burada otururlardı. Anneannesi elinde bir çıkın, içinde peynir, domates, bir parça ekmek. Güneşin batışını seyrederken anlattığı hikâyeler… Denizin dibindeki batık şehirler, geceleri limana gelip balıkçılarla konuşan yunuslar, kasabanın ilk fenercisinin sevdiği kadına yazdığı ama hiç göndermediği mektuplar. Nevin o zaman hepsinin masal olduğunu düşünürdü.',
            'Şimdi, suyun turuncudan mora dönüşünü izlerken, hangisinin masal olduğundan artık o kadar emin değildi.',
        ],
    ],
    [
        'title' => 'Evin Sesi',
        'blocks' => [
            'Nevin o gece anneannesinin yatağında uyuyamadı. Oda fazla sessizdi; ya da sessizlik fazla doluydu. Ahşap tavan kirişleri gece serinliğinde çıtırdıyor, pencere pervazındaki gevşek bir cam rüzgârla titriyor, uzaklarda bir köpek aralıklarla havlıyordu. İstanbul\'da gece hiçbir zaman sessiz olmazdı ama o gürültü anonimdi, kimseye ait değildi. Buradaki her ses bir şeye aitti: bu eve, bu sokağa, bu denize.',
            'Sabaha karşı kalktı, mutfakta çay demledi. Anneannesinin çaydanlığı, dibi kararmış emaye çaydanlık, ocağın üstünde tanıdık bir hışırtıyla kaynadı. Nevin bardağını alıp sedire oturdu ve nihayet konsolun üstündeki fotoğraflara baktı.',
            'En soldaki siyah beyazdı. Genç bir kadın, saçları iki yandan örülmüş, bir teknenin pruvasında gülümsüyordu. Arkasında liman, limanın arkasında bugünkünden çok daha az evin olduğu bir yamaç. Hayriye, diye düşündü Nevin. On sekiz yaşında olmalıydı. Yüzündeki ifade, fotoğrafı çeken kişiye bakan birinin ifadesiydi; sevgi ile muziplik arasında bir şey.',
            'Yanındaki fotoğrafta aynı kadın, bu kez kucağında bir bebekle. Nevin\'in annesi. Sonra annesinin okul fotoğrafları, annesinin düğünü, bir yaz günü bahçede çekilmiş kalabalık bir sofra. Ve en sağda, çerçevesi diğerlerinden yeni, Nevin\'in kendi fotoğrafı: dokuz yaşında, dişleri eksik, elinde kocaman bir kum kovası.',
            'Nevin fotoğrafı eline aldı. Arkasında kurşun kalemle bir not vardı, anneannesinin eğik el yazısıyla: "Nevin, kumdan kale yapmayı öğrendiği yaz. Kaleyi deniz aldı, ağlamadı. Dedi ki, yarın yenisini yaparım."',
            'Bir süre öylece oturdu. Sonra fotoğrafı yerine koydu ve işe koyuldu.',
            '## Envanter',
            'Restorasyon atölyesinde yıllardır yaptığı şeyi burada da yapmaya karar verdi: envanter. Her odayı tek tek dolaşacak, her eşyayı not edecek, durumunu yazacak, ne yapılacağına karar verecekti. Profesyonel bir mesafe. Duygusallığı dışarıda bırakan bir yöntem.',
            'Salondan başladı. Dikiş makinesi: Singer, ayaklı, muhtemelen altmışlı yıllardan. Çalışıyor mu, bilinmiyor. Ceviz konsol: el işçiliği, çekmecelerinde kakma motifler, bir ayağı sonradan onarılmış. Duvar aynası: sırrı yer yer dökülmüş, çerçeve oymalı. Sedir: minderleri yeniden kaplanmış, altındaki sandık…',
            'Sandığı açmaya çalıştı. Kilitliydi.',
            'Nevin anahtarlığı çıkardı. Kapı anahtarından başka iki küçük anahtar daha vardı; biri dolap anahtarına benziyordu, diğeri eski, dişleri aşınmış bir sandık anahtarı. Denedi. Olmadı. Anahtar kilide giriyor ama dönmüyordu.',
            '"Sonra," dedi kendi kendine ve deftere not düştü: Sedir sandığı, kilitli, anahtar uymuyor.',
            'Yatak odasına geçti. Gardırop anneannesinin elbiseleriyle doluydu; çoğu koyu renk, birkaçı çiçekli. En arkada, naftalin kokusu sinmiş bir torbanın içinde bir gelinlik. Nevin torbayı açmadı, yalnızca kumaşın kenarına dokundu. İpek. Sararmış ama sağlam.',
            'Çekmecelerden eski faturalar, ilaç kutuları, bir düğme kavanozu, iki paket iskambil kâğıdı, ipliğe dizilmiş kurutulmuş biberler çıktı. Bir de kalın bir defter. Kapağında hiçbir şey yazmıyordu. Nevin defteri açtı: sayfalar yemek tarifleriyle doluydu. Her tarifin altında küçük notlar vardı. "Hasan bunu sever." "Kızıma bayramda." "Tuzu az, Saniye tansiyonlu."',
            'Tariflerin arasında, defterin ortasına yakın bir yerde, bir sayfa yırtılmıştı. Temiz bir yırtık değildi; aceleyle koparılmış gibiydi. Yırtığın kenarında birkaç harf kalmıştı, yarım bir kelimenin başı: "Sev…"',
            'Nevin sayfayı parmaklarıyla düzeltti. Seven mi? Sevda mı? Sevgili mi? Belki yalnızca bir tatlının adıydı, sevdiği bir yemeğin. Deftere not düştü, sonra kaleminin ucunu bir süre kâğıdın üstünde tuttu, bir şey yazmadan.',
            '---',
            'Öğleden sonra sokağın başındaki bakkala gitti. Bakkal da değişmişti; eskiden tahta raflı, loş, anason ve sabun kokulu bir dükkândı, şimdi soğutucuları ve ışıklı tabelasıyla küçük bir market. Ama kasadaki adam, göbeği biraz daha büyümüş, saçları biraz daha azalmış haliyle, hâlâ Cemal Abi\'ydi.',
            '"Hayriye Teyze\'nin torunu!" dedi Nevin\'i görür görmez. "Başın sağ olsun kızım. Çok iyi kadındı. Veresiye defterinde bir kuruş borcu kalmazdı, ama başkasının borcunu sessizce kapattığı çok olurdu."',
            'Nevin ekmek, peynir, domates aldı. Parayı uzatırken Cemal Abi elini kaldırdı.',
            '"Olmaz. Bugün benden."',
            '"Cemal Abi, lütfen…"',
            '"Olmaz dedim." Adam poşeti uzattı, sonra sesini alçalttı. "Bir de şu var: Balıkçı Hasan seni soruyordu. Limanda, kırmızı teknenin yanında olur hep. Bir uğra ona. Anneannenle… eskiden… çok görüşürlerdi."',
            'Cümledeki duraksama Nevin\'in gözünden kaçmadı. Hasan bunu sever, diye düşündü. Tarif defterindeki not.',
            'Eve dönerken limana doğru saptı ama kırmızı tekneyi görünce adımları yavaşladı. Teknenin kıç tarafında, sırtı dönük, beyaz saçlı bir adam ağ örüyordu. Elleri hızlı ve kesindi, yüz yıl aynı hareketi yapmış gibi.',
            'Nevin yaklaşmadı. Henüz değil, dedi yine kendine. Bugün yeterince şey açmıştı: bir kapı, bir gardırop, bir defter. Bazı şeyler sırayla açılmalıydı.',
            'O gece yattığında evin seslerini tekrar dinledi. Kirişlerin çıtırtısı, camın titreyişi, uzaktaki köpek. Ve bu kez, bunların arasında, dün gece fark etmediği bir ses daha: salondan gelen hafif, düzenli bir tıkırtı. Sanki biri sedirin sandığına, çok yavaşça, parmaklarıyla vuruyordu.',
            'Nevin kalkıp baktı. Salonda kimse yoktu. Pencere açık kalmış, perde rüzgârla sandığın kapağına değip çekiliyordu.',
            'Pencereyi kapattı. Tıkırtı kesildi. Ama uykuya dalmadan önce aklında tek bir soru dönüp duruyordu: anneannesi, bu kadar düzenli bir kadın, neden bir sandığı kilitleyip anahtarını saklamıştı?',
        ],
    ],
    [
        'title' => 'Balıkçı Hasan',
        'blocks' => [
            'Üçüncü gün sabah, planına göre emlakçıyla görüşmesi gereken saatte, Nevin kendini limanda buldu.',
            'Kırmızı tekne yerindeydi. Adam da. Bu kez yüzü dönüktü; güneşten ve tuzdan kararmış, derin çizgilerle bölünmüş bir yüz. Gözleri ise şaşırtıcı biçimde açık renkti, denizin sığ yerlerindeki yeşil gibi.',
            '"Sen Nevin\'sin," dedi adam, soru sormadan.',
            '"Siz de Hasan Amca."',
            '"Amca," dedi adam, kelimeyi ağzında tartar gibi. Sonra gülümsedi. "Olsun. Amca olsun. Otur bakalım, çay var."',
            'Teknenin kenarındaki tahta sandığın üstüne oturdu Nevin. Hasan bir termostan iki plastik bardağa çay doldurdu. Bir süre konuşmadan içtiler. Martılar teknenin üstünde dönüyor, limanın öbür ucunda bir motor çalıştırılmaya çalışılıyordu.',
            '"Seni bebekken gördüm," dedi Hasan sonunda. "Annen seni ilk getirdiğinde. Hayriye seni kucağına aldı, buraya getirdi, denizi gösterdi. Daha gözlerini açalı bir ay olmuş. Dedi ki, bu kız denizi sevecek."',
            '"Sevdim," dedi Nevin. "Sonra… uzaklaştım."',
            '"Deniz uzaklaşanı bekler." Hasan omuz silkti. "Sabırlıdır. İnsanlardan daha sabırlı."',
            'Nevin bardağını iki eliyle tuttu. Soruyu nasıl soracağını bilmiyordu. Sonunda doğrudan sordu:',
            '"Anneannemle çok görüşürmüşsünüz. Cemal Abi öyle dedi."',
            'Hasan uzun süre cevap vermedi. Elindeki ağın bir düğümünü çözdü, yeniden attı. Sonra denize baktı.',
            '"Altmış yıl," dedi. "Altmış yıl görüştük. Ama belki de hiç görüşmedik. Nasıl anlatsam…"',
            '## Altmış Yıl',
            'Hikâye, anlatıldığı haliyle, basitti. Hasan on dokuz, Hayriye on yedi yaşındayken kasabanın yaz şenliğinde tanışmışlar. Hasan bir balıkçının oğlu, Hayriye kasabanın tek eczacısının kızı. Bir yaz boyunca gizlice buluşmuşlar; akşamları iskelenin ucunda, sabahları zeytinliklerin arasında. Hasan, babasının teknesiyle Hayriye\'yi adaya götürmüş, orada Hayriye ilk kez yüzme öğrenmiş.',
            '"Eczacı razı olmadı," dedi Hasan. "Balıkçı oğluna kız mı verilir? O zamanlar öyleydi. Beni askere gönderdiler, Hayriye\'yi İzmir\'de bir memurla evlendirdiler. Ben döndüğümde evliydi. Kocası iyi adamdı, haksızlık etmeyeyim. Kızları oldu, annen. Sonra kocası erken öldü, Hayriye buraya, babasının evine döndü."',
            '"Siz?"',
            '"Ben evlendim. Karım da iyi kadındı. Rahmetli oldu, on beş yıl önce." Hasan ağı dizlerinin üstüne bıraktı. "Hayriye ile her gün görüştük sonra. Her gün. Bakkalda, limanda, şenlikte. Selamlaştık, hal hatır sorduk. Bayramlarda ben ona balık getirdim, o bana reçel verdi. Altmış yıl. Ama bir kere bile… o yazdan bir kere bile konuşmadık."',
            'Nevin tarif defterini düşündü. Hasan bunu sever. Yırtılmış sayfayı düşündü. Sev…',
            '"Hiç mi?"',
            '"Hiç." Hasan başını salladı. "Bazen insanın bir şeyi konuşmaması, o şeyi korumasıdır. Konuşursan küçülür. Kelimelere sığar. Konuşmazsan olduğu gibi kalır, kocaman."',
            'Uzun bir sessizlik oldu. Martılardan biri teknenin küpeştesine kondu, başını yana eğip onlara baktı.',
            '"Sana bir şey sormak istiyorum," dedi Hasan sonunda. Sesi değişmişti, daha kısık. "Hayriye… bir şey bıraktı mı? Bana dair?"',
            'Nevin bir an düşündü. Sandık. Kilitli sandık. Uymayan anahtar.',
            '"Bilmiyorum," dedi dürüstçe. "Evde kilitli bir sandık var. Anahtarı bulamadım."',
            'Hasan\'ın yüzünden bir şey geçti; bir gölge, bir ışık, ikisi birden. Sonra ayağa kalktı, teknenin kabinine girdi ve elinde küçük, pirinç bir anahtarla döndü. Anahtarın başına kırmızı bir iplik bağlanmıştı, rengi solmuş.',
            '"O yaz," dedi, "ona bir sandık yaptım. Küçük bir sandık, çam tahtasından. Mektuplarını saklasın diye. İki anahtarı vardı. Birini ona verdim, birini kendime sakladım. Altmış yıl…" Sesi kesildi. Anahtarı Nevin\'e uzattı. "Belki bu açar. Belki başka sandıktır. Bilmiyorum."',
            'Nevin anahtarı aldı. Avucunda soğuk ve ağırdı.',
            '"Benimle gelmek ister misiniz?" diye sordu.',
            'Hasan uzun süre denize baktı. Sonra başını iki yana salladı.',
            '"Hayır. Sen aç. Eğer içinde bir şey varsa, ve eğer bana söylenmesi gerekiyorsa… sen söylersin." Hafifçe gülümsedi. "Altmış yıl bekledim. Bir akşam daha bekleyebilirim."',
            '---',
            'Nevin eve dönerken anahtarı cebinde, eliyle sıkı sıkı tutuyordu. Yokuşu çıkarken Saniye Teyze yine balkondaydı, bu kez elinde bir sepet çamaşırla.',
            '"Hasan\'la konuştun," dedi kadın. Yine soru değildi.',
            '"Nereden bildiniz?"',
            '"Yüzünden. Hayriye de Hasan\'la konuştuktan sonra hep öyle yürürdü. Sanki bir şey taşır gibi, ama hafif bir şey."',
            'Nevin kapıyı açtı, bu kez kaldırmasına gerek kalmadan. Salona girdi, sedirin önünde diz çöktü ve Hasan\'ın anahtarını kilide soktu.',
            'Anahtar döndü.',
        ],
    ],
    [
        'title' => 'Kilitli Sandık',
        'blocks' => [
            'Sandığın kapağı ağırdı. Nevin iki eliyle kaldırdı ve menteşelerin çıkardığı uzun gıcırtıyla birlikte içeriden bir koku yükseldi: lavanta, kâğıt ve çok eski bir tahtanın kuru, tatlı kokusu.',
            'İlk gördüğü şey bir örtüydü. Beyaz, kenarları elde işlenmiş bir örtü, özenle katlanmış. Nevin örtüyü kaldırdı. Altında bir şey daha vardı: çam tahtasından yapılmış küçük bir sandık, bir ayakkabı kutusundan biraz büyük, kapağına bir martı figürü oyulmuş.',
            'Sandığın içinde bir sandık. Nevin güldü, sesli, kendine şaşırarak. Anneannesi… Anneannesi ne yapmıştı?',
            'Küçük sandığın kilidi yoktu, yalnızca bir mandal. Nevin mandalı açtı.',
            'İçi mektuplarla doluydu.',
            'Yüzlerce değil ama onlarca. Bazıları zarfında, bazıları yalnızca katlanmış kâğıtlar. Hepsi aynı el yazısıyla yazılmıştı, anneannesinin eğik ve düzgün el yazısıyla. Ve hepsinin üstünde, ya zarfta ya kâğıdın dış yüzünde, aynı isim: Hasan\'a.',
            'Hiçbiri pullu değildi. Hiçbiri gönderilmemişti.',
            '## İlk Mektup',
            'Nevin mektupları tarihlerine göre sıraladı. Anneannesi hepsine tarih atmıştı; bazılarına yalnızca yıl, bazılarına gün ve ay. İlki, en sararmış olanı, 1961 yılının eylül ayından.',
            'Açmak için uzun süre bekledi. Bunun doğru olup olmadığını düşündü. Bu mektuplar Hasan\'a yazılmıştı, ona değil. Ama anneannesi sandığı kilitlemiş ve anahtarlardan birini, kendi anahtarlığına değil, belki de hiç açılmasın diye başka yere koymuştu. Öbür anahtar ise altmış yıldır Hasan\'daydı. Anneannesi evi Nevin\'e bırakmıştı. Sandığı da.',
            'Belki bunu istemişti. Belki birinin açmasını, ama kendisinin değil.',
            'Nevin ilk mektubu açtı.',
            '> Hasan, bugün İzmir\'e gidiyorum. Babam arabayı kapıya getirtti, eşyalarım yüklendi. Sana yazıyorum çünkü sana söyleyemem. Söylersem gitmem, gitmezsem babam… Bilmiyorum babam ne yapar. Bilmediğim bir şeyden korkmak, bildiğim bir şeyi kaybetmekten daha kolay geliyor bana şimdi. Ne kadar korkağım, değil mi? Adada bana yüzmeyi öğretirken demiştin ki, suya güvenirsen su seni taşır. Ben suya güvenmeyi öğrendim, Hasan. Ama kendime güvenmeyi öğrenemedim.',
            'Mektup böyle devam ediyordu. Bir sayfa, bir buçuk sayfa. Sonunda imza yoktu. Yalnızca bir cümle: "Bu mektubu da göndermeyeceğim. Sen bil diye yazıyorum ama sen bilmeyeceksin."',
            'Nevin mektubu dizlerinin üstüne bıraktı. Pencereden giren öğle ışığı odada yavaşça yer değiştiriyordu.',
            '## Yıllar',
            'Sonraki mektuplar yılları kat ediyordu. 1963: evliliğin ilk yılı, İzmir\'deki evin küçük balkonu, kocasının nazikliği ve bu nazikliğin ona verdiği suçluluk. 1965: annesinin doğumu. "Bir kızım oldu, Hasan. Adını sana söylesem güler misin? Denizin rengine benzer bir isim koymak istedim, kocam razı olmadı. Adı Gülsüm oldu, anneannemin adı. Ama ben ona gizlice Deniz diyorum."',
            'Nevin bunu bilmiyordu. Annesi hiç anlatmamıştı; belki bilmiyordu.',
            '1972: kocasının hastalığı. 1974: ölümü. 1975: kasabaya dönüş. Ve bu mektupta, ilk kez, bir değişiklik:',
            '> Bugün seni limanda gördüm. Kırmızı teknen hâlâ duruyor, boyası yenilenmiş. Sen de duruyorsun, saçına beyaz düşmüş. Selam verdin. Ben de selam verdim. Nasılsın dedin, iyiyim dedim. Evlenmişsin, biliyorum. Karın iyi bir kadın, onu da biliyorum; bakkalda gördüm, bana gülümsedi. Hasan, on dört yıl sonra seninle yan yana durdum ve tek bir kelime söyleyemedim. Söylememeyi seçtim. Çünkü artık söylenecek şey bir kelime değil, bir ömür. Bir ömür nasıl söylenir?',
            'Nevin okumaya ara verdi. Mutfağa gidip su içti, ellerini yüzüne götürdü. Sonra geri döndü.',
            'Mektuplar seyrekleşiyordu. Seksenlerden birkaç tane, doksanlardan bir tane, iki binlerden hiç. Sonra, çok uzun bir aradan sonra, son mektup. Tarihi: geçen yılın kasımı. Anneannesinin ölümünden üç ay önce.',
            'Bu mektubun kâğıdı diğerlerinden farklıydı: yırtılmış bir defter sayfası. Kenarında tanıdık bir yırtık izi. Nevin tarif defterini yatak odasından getirdi, sayfayı yırtık yerine tuttu. Tam oturdu. Sayfanın üst köşesinde, yırtığın öbür yanında kalan harflerle birleşince kelime tamamlanıyordu: "Sevgili Hasan."',
            'Nevin son mektubu açmadı.',
            'Onu açması gereken kişinin o olmadığını biliyordu.',
        ],
    ],
    [
        'title' => 'Mektuplar',
        'blocks' => [
            'O akşam limana indiğinde güneş çoktan batmıştı. İskelede tek tük fener yanıyor, suyun üstünde titrek sarı halkalar çiziyordu. Kırmızı teknenin kabininde ışık vardı.',
            'Nevin küçük sandığı kucağında taşıyordu. İçindeki bütün mektuplarla, en üstte o son sayfa.',
            'Hasan onu görünce ayağa kalktı. Hiçbir şey sormadı. Gözleri sandığa, sonra Nevin\'in yüzüne, sonra yine sandığa gitti. Martı figürünü görünce eli titredi.',
            '"Yaptığınız sandık," dedi Nevin. "İçinde anneannemin size yazdığı mektuplar var. Altmış yılın mektupları. Hiçbirini göndermemiş."',
            'Hasan sandığı iki eliyle aldı. Kucağına koydu, tekneden iskeleye uzanan tahtanın üstüne oturdu. Bir süre yalnızca kapağındaki martıyı okşadı, parmak uçlarıyla, sanki kör biri bir yüzü tanımaya çalışır gibi.',
            '"İlkini okudum," dedi Nevin. "Ve birkaçını daha. Özür dilerim. Bilmem gerekiyordu, size vermeden önce. Ama sonuncusunu okumadım. O sizin."',
            'Hasan başını salladı. Sandığı açtı, en üstteki yırtık sayfayı aldı. Fenerin ışığına tuttu. Gözlükleri yoktu; kâğıdı yüzünden uzaklaştırıp yaklaştırarak, dudakları hafifçe kıpırdayarak okudu.',
            'Nevin bakmamaya çalıştı. Denize baktı, karşı adanın karanlık siluetine, gökyüzünde yavaşça beliren yıldızlara. Ama Hasan\'ın omuzlarının titrediğini gözünün ucuyla görüyordu.',
            'Uzun bir süre sonra Hasan kâğıdı katladı, göğüs cebine koydu.',
            '"Ne yazıyor, biliyor musun?" dedi. Sesi ıslaktı ama sakin.',
            '"Hayır."',
            '"Yazıyor ki…" Hasan durdu, yutkundu. "Yazıyor ki, bu mektubu da göndermeyeceğim, çünkü artık göndermeme gerek yok. Sen biliyorsun, ben biliyorum. Altmış yıl boyunca bildik. Her sabah limanda selamlaştığımızda, her bayram kapıma balık bıraktığında, her seferinde reçel kavanozunu uzattığımda. Kelimelere dökmedik diye olmamış sayılmaz. Olmayan şeyler için de mektup yazılır, Hasan. Ama bu mektup, olan bir şey için."',
            'Hasan sustu. Nevin de sustu. Tekne hafif dalgada yavaşça sallanıyor, halatlar iskele babalarına sürtünerek gıcırdıyordu.',
            '"Bir de," dedi Hasan, "sonunda bir cümle daha var. Torunum bir gün gelirse, bu sandığı ona ver. Ben veremeyeceğim, çünkü gelmeyecek diye korkuyorum. Ama gelirse, deniz gibi olsun. Beklesin, affetsin, geri dönsün."',
            'Nevin başını ellerinin arasına aldı. Ağlamıyordu. Ya da ağlıyordu ama bu, bildiği ağlamaya benzemiyordu; içinde bir düğüm yavaşça çözülüyor, çözüldükçe yer açıyordu.',
            '---',
            '## Gece Yarısı',
            'O gece Hasan ona bütün hikâyeyi anlattı. Bu kez eksiksiz. O yazın bütün akşamlarını, adadaki koyun adını (Karataş), Hayriye\'nin ilk kulaç attığında yuttuğu tuzlu suyu, eczacının Hasan\'ı dükkândan kovduğu günü. Askerlikte yazdığı ama onun da göndermediği mektupları, o mektupları döndüğünde denize attığını.',
            '"İkimiz de göndermedik," dedi Hasan acı bir gülümsemeyle. "İkimiz de korktuk. Farkımız şu: o sakladı, ben attım."',
            '"Belki de bu yüzden bıraktı sandığı bana," dedi Nevin. "Siz attığınız için. Biri saklasın diye."',
            'Hasan ona uzun uzun baktı.',
            '"Gözlerin onun gözleri," dedi. "Saniye de söylemiştir. Ama ağzın… ağzın başka. Konuşan bir ağız. O hiç konuşamadı, ben de. Sen konuş, kızım. Ne yapacaksan, kime ne söyleyeceksen, konuş. Mektubu cebinde taşıma."',
            'Nevin eve döndüğünde saat ikiyi geçiyordu. Telefonunu çevirdi. Ortağından üç mesaj vardı, müşterilerden iki arama, bir de İstanbul\'daki emlakçıdan kısa bir not: "Yarınki görüşmeyi teyit eder misiniz?"',
            'Nevin telefonun ekranına uzun süre baktı. Sonra bir mesaj yazmaya başladı. Silip tekrar yazdı. Sonunda şunu gönderdi: "Görüşmeyi iptal ediyorum. Ev satılık değil."',
            'Gönderdikten sonra kalbinin hızla attığını fark etti. Konuş, demişti Hasan. Mektubu cebinde taşıma.',
            'Ertesi sabah annesini aradı. Yıllardır yapmadığı bir şeydi bu: sabah, hiçbir sebep yokken, yalnızca konuşmak için aramak.',
            '"Anne," dedi, "sana bir şey sormak istiyorum. Anneannem sana hiç Deniz dedi mi?"',
            'Telefonun öbür ucunda uzun bir sessizlik oldu. Sonra annesinin sesi, beklemediği kadar yumuşak:',
            '"Nereden biliyorsun bunu?"',
        ],
    ],
    [
        'title' => 'Fırtına Gecesi',
        'blocks' => [
            'Fırtına, eylülün ilk haftasında geldi.',
            'Sabahtan belliydi. Gökyüzü alışılmadık bir sarıya bürünmüş, deniz yağ gibi durgunlaşmıştı. Balıkçılar tekneleri limanın iç tarafına çekiyor, halatları ikiye katlıyordu. Kasabanın yaşlıları kahvehanede toplanmış, pencerelerden dışarı bakıp başlarını sallıyorlardı.',
            '"Poyraz geliyor," dedi Cemal Abi, Nevin ekmek almaya geldiğinde. "Üç günlük poyraz. Kapını pencereni iyi kapa. Hayriye Teyze\'nin evinin arka kepengi gevşektir, bir bak ona."',
            'Nevin artık üç haftadır kasabadaydı. İstanbul\'daki atölyeye bir kez gidip gelmiş, en acil işleri ortağına devretmiş, geri dönmüştü. Ortağı onu anlamıştı; ya da anlamamıştı ama sormamıştı, ki bu da bir tür anlayıştı. Nevin evin salonunu küçük bir atölyeye çevirmiş, anneannesinin ceviz konsolunu restore etmeye başlamıştı. Kakma motiflerin arasına yıllarca birikmiş kiri kürdanla temizlerken bazen saatlerin nasıl geçtiğini fark etmiyordu.',
            'Öğleden sonra rüzgâr başladı. Önce hafif, sonra giderek sertleşen darbelerle. Akşama doğru yağmur da katıldı; yatay, kamçı gibi bir yağmur. Nevin arka kepengi tel ile bağladı, pencerelerin önüne havlu sıkıştırdı, mumları ve el fenerini masanın üstüne dizdi.',
            'Elektrikler saat dokuzda kesildi.',
            '## Karanlıkta',
            'Nevin mumu yaktı ve sedire oturdu. Rüzgâr evin etrafında uğulduyor, kiremitlerin arasından ıslık gibi sesler çıkarıyordu. Denizin sesi, normalde bir fısıltı, şimdi bir kükreme olmuştu; dalgaların limanın mendireğine çarpışı yokuşun başından bile duyuluyordu.',
            'Kapı çalındı.',
            'Nevin fenerle kapıya gitti. Saniye Teyze, başında bir naylon poşet, elinde bir tencere.',
            '"Tek başına korkarsın diye geldim," dedi kadın, içeri girerken. "Hem ben de korkuyorum. Hayriye ile fırtınalarda hep birlikte otururduk. Mercimek çorbası getirdim."',
            'Mum ışığında çorbalarını içtiler. Saniye Teyze anlattı: 1987 fırtınasını, limandaki üç teknenin nasıl battığını, Hayriye\'nin o gece balıkçıların ailelerine nasıl çay taşıdığını. 1999 depremini, kasabanın o gece nasıl tümüyle sokağa döküldüğünü. Hayriye\'nin herkes için battaniye ve ekmek dağıttığını.',
            '"Kendi derdini hiç anlatmazdı," dedi Saniye Teyze. "Ama herkesin derdini dinlerdi. Ben ona elli yıl derdimi anlattım. O bana bir kere bile anlatmadı. Bir kere hariç."',
            '"Ne zaman?"',
            '"Geçen kış. Hastalığı başlamıştı. Bir akşam böyle oturuyorduk, dedi ki: Saniye, ben bir mektup yazdım, gönderemedim. Dedim ki, kime? Güldü. Dedi ki, biliyorsun kime. Ben de biliyordum. Bütün kasaba biliyordu kızım. Altmış yıl. Kimse söylemedi, ama herkes biliyordu."',
            'Nevin mumun alevine baktı. Rüzgâr bir an durdu, sonra daha şiddetli bir darbeyle geri geldi.',
            'Tam o sırada, fırtınanın uğultusunun arasından, uzakta bir ses duyuldu: bir teknenin sireni. Uzun, kesik, bir daha uzun.',
            'Saniye Teyze\'nin yüzü değişti.',
            '"Bu imdat," dedi. "Biri denizde."',
            '---',
            '## Liman',
            'Nevin bir yağmurluk kaptığı gibi yokuştan aşağı koştu. Limana indiğinde kasabanın yarısı oradaydı; fenerler, el lambaları, ıslak yüzler. İskelede bir kalabalık toplanmış, denize bakıyordu.',
            '"Ne oldu?" diye bağırdı Nevin, rüzgârın içinden.',
            'Cemal Abi döndü. Yüzü bembeyazdı.',
            '"Hasan," dedi. "Kırmızı tekne. Halatı koptu, akıntı adaya doğru sürüklüyor. Hasan da içinde. Tekneyi kurtarmaya çalışırken…"',
            'Nevin iskelenin ucuna koştu. Karanlıkta, dalgaların arasında, bir kırmızılık görünüp kayboluyordu. Teknenin kabinindeki ışık, bir yanıp bir sönüyordu.',
            '"Kimse çıkmıyor mu?" diye bağırdı.',
            '"Bu havada çıkılmaz kızım!" dedi yaşlı bir balıkçı. "Sahil güvenliği aradık. Yarım saat."',
            'Yarım saat. Nevin dalgalara baktı. Tekne adaya, Karataş koyunun kayalıklarına doğru sürükleniyordu.',
            'Sonra bir şey oldu. Teknenin kabinindeki ışık sabitlendi. Motorun sesi, fırtınanın içinden, kesik kesik duyulmaya başladı. Kırmızı tekne, dalgalarla boğuşarak, yavaşça burnunu limana çevirdi.',
            'Kalabalıktan bir uğultu yükseldi. Hasan motoru çalıştırmayı başarmıştı.',
            'Tekne limana girdiğinde saat on biri geçiyordu. On kişi halata sarıldı, tekneyi iskeleye çekti. Hasan kabinden çıktığında sırılsıklamdı, alnında bir kesik vardı, ama ayaktaydı. Ve göğsüne, yağmurluğunun içine, bir şey bastırıyordu.',
            'Nevin ona ulaştığında Hasan elini açtı. Martı figürlü küçük sandık. Islak, ama sağlam.',
            '"Teknedeydi," dedi Hasan, nefes nefese. "Her gece yanımda tutuyordum. Halat kopunca… önce sandığı düşündüm. Tekneyi değil. Sandığı. Deli miyim?"',
            'Nevin güldü, ağladı, ikisini birden yaptı. Hasan\'ı kolundan tuttu.',
            '"Değilsiniz," dedi. "Altmış yıl sonra ilk kez bir şeyi bırakmadınız."',
        ],
    ],
    [
        'title' => 'Kıyıda Bir Sabah',
        'blocks' => [
            'Fırtınadan sonraki sabah kasaba yıkanmış gibiydi.',
            'Gökyüzü o kadar temizdi ki karşıdaki adanın ağaçları tek tek sayılabiliyordu. Sokaklarda kırık dallar, devrilmiş saksılar, limanın kenarına vurmuş yosun yığınları vardı. İnsanlar kapı önlerine çıkmış, süpürüyor, topluyor, birbirine hasar soruyordu. Ama havada bir hafiflik vardı; tehlike geçmişti, herkes sağdı.',
            'Nevin erkenden kalktı. Mutfakta anneannesinin emaye çaydanlığında çay demledi. Sonra tezgâhın üstünde, üç haftadır dokunmadığı kavanozu aldı: "Ayva, 2023."',
            'Kapağını açtı. Ayvanın kokusu mutfağa yayıldı; tatlı, ekşimsi, sonbahar gibi. Bir kaşık aldı, ekmeğin üstüne sürdü. Yedi. Tadı, çocukluğunun bütün kahvaltılarının tadıydı.',
            'Kavanozdan küçük bir kâseye biraz reçel koydu, kapattı ve evden çıktı.',
            '## Son Ziyaret',
            'Hasan limandaydı. Alnındaki kesiğe bir yara bandı yapıştırılmıştı. Kırmızı teknenin yanında durmuş, fırtınanın verdiği hasarı inceliyordu: kırık bir küpeşte, yırtılmış bir branda, bir de motor kapağının üstünde derin bir çizik.',
            '"Onarılır," dedi, Nevin\'i görünce. "Her şey onarılır. Senin mesleğin değil mi bu?"',
            '"Benim mesleğim," dedi Nevin gülümseyerek. Kâseyi uzattı. "Anneannemin son reçeli. Ayva. Size."',
            'Hasan kâseyi aldı. Uzun süre içine baktı. Sonra parmağının ucuyla biraz alıp tattı. Gözlerini kapattı.',
            '"Her yıl," dedi. "Her yıl bir kavanoz verirdi. Kapıma bırakırdı, zil çalmadan. Ben de bir kova balık bırakırdım onun kapısına. Altmış yıl böyle konuştuk. Reçelle ve balıkla."',
            '"Bu yıl ben getirdim," dedi Nevin. "Bir de şunu söylemek istiyorum: Evi satmıyorum. Burada kalacağım. En azından bir süre. İstanbul\'daki atölyeyi küçültüyorum, burada bir atölye açacağım. Eski mobilya, eski kapılar, eski sandıklar… Bu kasabada onarılmayı bekleyen çok şey var."',
            'Hasan gözlerini açtı. Ona baktı. Sonra, Nevin\'in hiç beklemediği bir şey yaptı: güldü. Gerçek, içten, yaşlı bir adamın bütün göğsünden gelen bir kahkaha.',
            '"Hayriye bilirdi," dedi. "Deniz bekleyeni geri getirir, derdi. Ben inanmazdım."',
            '---',
            'O gün öğleden sonra ikisi birlikte kırmızı tekneyi onarmaya başladılar. Hasan küpeşteyi söktü, Nevin yeni tahtayı ölçtü, kesti, zımparaladı. Hasan motor kapağındaki çiziği doldurmayı öğretti ona; Nevin de Hasan\'a ahşabın damarına göre zımpara yapmayı. Akşama doğru tekne neredeyse eskisi gibiydi. Neredeyse. Yeni küpeştenin rengi eskisinden biraz açıktı.',
            '"Boyarız," dedi Nevin.',
            '"Boyamayalım," dedi Hasan. "Kalsın öyle. Onarıldığı belli olsun. Onarılmış şeyler daha güzeldir."',
            'Nevin buna itiraz etmedi. Restorasyonda buna bir ad verirlerdi; görünür onarım. Kırığı saklamak yerine göstermek, onu nesnenin hikâyesinin bir parçası yapmak. Japonların altınla yapıştırdıkları kırık çanaklar gibi.[[dn:Kintsugi: kırılan seramiği altın ya da gümüş tozu karıştırılmış vernikle onaran Japon geleneği. Kırık gizlenmez, nesnenin geçmişinin bir parçası olarak öne çıkarılır.]] Hasan bu kelimeyi bilmiyordu ama altmış yıllık hayatı ona aynı şeyi öğretmişti.',
            '## Sabah',
            'Ertesi sabah, güneş doğmadan, Nevin limana indi. İskelenin ucuna yürüdü, ayakkabılarını çıkardı ve ayaklarını suya sarkıttı. Su, eylül sabahının serinliğindeydi.',
            'Bir süre sonra yanına biri oturdu. Hasan. Elinde iki bardak çay.',
            'Konuşmadılar. Gerek yoktu. Karşıdaki adanın arkasından gökyüzü önce griye, sonra pembeye, sonra altın rengine döndü. Martılar uyanıp limanın üstünde dönmeye başladı. Uzaktan ilk teknelerin motor sesleri geldi.',
            'Güneş adanın üstünden yükselip suyun üstüne ilk ışığını düşürdüğünde Nevin, anneannesinin hikâyelerini düşündü. Batık şehirleri, yunusları, hiç gönderilmemiş mektupları. Hangisinin masal olduğunu artık gerçekten bilmiyordu. Belki hiçbiri. Belki hepsi. Belki masal ile gerçek arasındaki fark, yalnızca birinin onu anlatmaya cesaret edip etmemesiydi.',
            '"Bugün ne yapacaksın?" diye sordu Hasan sonunda.',
            'Nevin güneşe baktı. Denize. Arkasındaki kasabaya, yokuşun sonundaki mavi kapılı eve.',
            '"Bir mektup yazacağım," dedi. "Ve göndereceğim."',
            'Hasan başını salladı. Çayından bir yudum aldı. Güneş yükseldi.',
            'Kıyıda, bir sabah daha başladı.',
        ],
    ],
];
